import {describe,it,expect} from 'vitest';
import {budgetReport,reportTarget,varianceLabel} from '../src/budgetReport';
import {filtered} from '../src/finance';
import type {Ledger,Entry,PeriodGoal} from '../src/types';
const profile={user_id:'u',currency:'PKR' as const,planning_currency:'PKR' as const,timezone:'Asia/Karachi',income_target:0,spending_target:0,saving_target:0,investment_target:0,emergency_target:0,emergency_contribution:0};
function ledger():Ledger{return {profile,categories:[{id:'e',user_id:'u',name:'Food',kind:'expense',archived:false,essential:false,emergency:false},{id:'s',user_id:'u',name:'Savings',kind:'saving',archived:false,essential:false,emergency:false},{id:'i',user_id:'u',name:'Investments',kind:'investment',archived:false,essential:false,emergency:false}],subcategories:[{id:'g',user_id:'u',category_id:'e',name:'Groceries',archived:false}],entries:[],goals:[]};}
const entry=(id:string,category_id:string,amount_minor:number,date='2026-01-01',withdrawal=false,subcategory_id:string|null=null,currency:Entry['currency']='PKR'):Entry=>({id,user_id:'u',category_id,amount_minor,date,withdrawal,subcategory_id,currency,notes:''});
const goal=(kind:PeriodGoal['kind'],target_minor:number,period='2026-01',category_id:string|null=null):PeriodGoal=>({id:kind+period+(category_id??''),user_id:'u',currency:'PKR',kind,target_minor,period,category_id});
const filter={year:'2026',month:'01',category:'all'};
describe('compact budget report',()=>{
 it('keeps zero and missing plans distinct and never divides by zero',()=>{const l=ledger();l.goals=[goal('expense',0)];const r=budgetReport(l,filter);expect(r.main[0]).toMatchObject({target:0,percent:null,remaining:0});expect(r.main[1]).toMatchObject({target:null,percent:null,remaining:null});});
 it('expense overspending is a warning; exceeded contribution targets are progress',()=>{const l=ledger();l.goals=[goal('expense',100),goal('saving',100),goal('investment',100)];l.entries=[entry('1','e',150),entry('2','s',200),entry('3','s',50,undefined,true),entry('4','i',150)];const r=budgetReport(l,filter);expect(r.main.map(varianceLabel)).toEqual(['Over budget','Above target','Above target']);expect(r.main[1]).toMatchObject({actual:150,contribution:200,withdrawal:50,remaining:-50,percent:150});expect(r.values).toEqual({income:0,expense:150,saving:150,investment:150});});
 it('reconciles category/child/direct and historical archived totals within the period/currency',()=>{const l=ledger();l.categories[0].archived=true;l.subcategories![0].archived=true;l.entries=[entry('1','e',100,undefined,false,'g'),entry('2','e',25),entry('3','e',999,'2026-02-01'),entry('4','e',999,undefined,false,null,'USD')];const r=budgetReport(l,filter);expect(r.main[0].actual).toBe(125);expect(r.categories.filter(c=>c.kind==='expense').reduce((v,c)=>v+c.actual,0)).toBe(125);expect(r.subcategories[0]).toMatchObject({actual:100,archived:true,count:1});});
 it('year comparisons aggregate monthly plans and ignore historical annual targets',()=>{const l=ledger();l.profile={...profile,spending_target:100};l.goals=[goal('expense',200,'2026-02'),goal('expense',99999,'2026')];expect(reportTarget(l,{...filter,month:'all'},'expense')).toMatchObject({target:1300});l.profile={...profile};expect(reportTarget(l,{...filter,month:'all'},'expense').target).toBe(null);});
 it('prorates inclusive custom boundaries and leap days, rounding each month in minor units',()=>{const l=ledger();l.goals=[goal('expense',3100,'2024-01'),goal('expense',2900,'2024-02')];const f={...filter,startDate:'2024-01-31',endDate:'2024-02-29'};expect(reportTarget(l,f,'expense')).toMatchObject({target:3000});l.entries=[entry('1','e',10,'2024-01-30'),entry('2','e',20,'2024-01-31'),entry('3','e',30,'2024-02-29'),entry('4','e',40,'2024-03-01')];expect(budgetReport(l,f).main[0].actual).toBe(50);expect(filtered(l.entries,f).map(e=>e.id)).toEqual(['3','2']);});
 it('category limits are included within overall expense totals and currency defaults stay separate',()=>{const l=ledger();l.profile={...profile,spending_target:100};l.goals=[goal('expense',100),goal('expense',60,'2026-01','e')];const r=budgetReport(l,filter);expect(r.main[0].target).toBe(100);expect(r.categories[0].target).toBe(60);l.profile={...l.profile,currency:'USD'};expect(reportTarget(l,filter,'expense').target).toBe(null);});
 it('edits and deletions recalculate and list filters never change main totals',()=>{const l=ledger();l.entries=[entry('1','e',100),entry('2','s',50)];expect(budgetReport(l,{...filter,category:'s',subcategory:'g'}).main[0].actual).toBe(100);l.entries[0].amount_minor=200;expect(budgetReport(l,filter).main[0].actual).toBe(200);l.entries=[];expect(budgetReport(l,filter).main[0].actual).toBe(0);});
});
