import { describe, expect, it } from 'vitest';
import { monthlyGoalSum, periodGoalRows } from '../src/goals';
import type { Ledger, PeriodGoal } from '../src/types';
const ledger: Ledger = {categories:[{id:'expense',user_id:'a',kind:'expense',name:'Bills',essential:true,emergency:false,archived:true},{id:'saving',user_id:'a',kind:'saving',name:'Savings',essential:false,emergency:true,archived:false}],entries:[{id:'1',user_id:'a',category_id:'expense',date:'2026-01-01',currency:'PKR',amount_minor:150,withdrawal:false,notes:''},{id:'2',user_id:'a',category_id:'saving',date:'2026-01-02',currency:'PKR',amount_minor:70,withdrawal:true,notes:''},{id:'3',user_id:'a',category_id:'expense',date:'2026-01-01',currency:'USD',amount_minor:9999,withdrawal:false,notes:''}],profile:{user_id:'a',currency:'PKR',timezone:'UTC',income_target:1000,spending_target:200,saving_target:100,investment_target:0,emergency_target:0,emergency_contribution:0}};
const goal=(period:string,target:number,category_id:string|null=null):PeriodGoal=>({id:period+(category_id??''),user_id:'a',period,currency:'PKR',kind:'expense',category_id,target_minor:target});
describe('period goals',()=>{
  it('keeps monthly, yearly and other-currency targets independent, including zero limits',()=>{const l={...ledger,goals:[goal('2026-01',0),goal('2026',2400),{...goal('2026-01',999),currency:'USD' as const}]};const jan=periodGoalRows(l,{year:'2026',month:'01',category:'saving'});expect(jan.find(r=>r.kind==='expense')?.target).toBe(0);expect(jan.find(r=>r.kind==='expense')?.actual).toBe(150);expect(periodGoalRows(l,{year:'2026',month:'02',category:'all'}).find(r=>r.kind==='expense')?.target).toBe(200);expect(periodGoalRows(l,{year:'2026',month:'all',category:'all'}).find(r=>r.kind==='expense')?.target).toBe(2400);});
  it('counts withdrawals and archived category spending once and keeps currencies separate',()=>{const rows=periodGoalRows({...ledger,goals:[goal('2026-01',100,'expense')]},{year:'2026',month:'01',category:'all'});expect(rows.find(r=>r.category_id==='expense')?.actual).toBe(150);expect(rows.find(r=>r.kind==='saving')?.actual).toBe(-70);});
  it('derives annual goals from twelve monthly plans without modifying them',()=>{const l={...ledger,goals:[goal('2026-01',0),goal('2026-02',300)]};expect(monthlyGoalSum(l,'2026','expense')).toBe(2300);expect(periodGoalRows(l,{year:'2026',month:'all',category:'all'}).find(r=>r.kind==='expense')?.target).toBeNull();expect(l.goals).toHaveLength(2);expect(periodGoalRows(l,{year:'all',month:'all',category:'all'})).toEqual([]);});
});
