import { expect, test } from '@playwright/test';
test('quick expenses and independent monthly/yearly goals persist after reload',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'Explore the demo'}).click();
  await page.getByLabel('Expense amount',{exact:false}).fill('12.50');
  await page.getByRole('combobox',{name:'Expense category',exact:true}).selectOption({label:'Groceries'});
  await page.getByText('Change date or add a note',{exact:true}).click();
  await page.getByLabel('Expense date',{exact:true}).fill('2026-02-03');
  await page.getByLabel('Expense note (optional)',{exact:true}).fill('Quick entry verification');
  await page.getByRole('button',{name:'Save expense',exact:true}).click();
  await expect(page.getByLabel('Month',{exact:true})).toHaveValue('02');
  await expect(page.getByText('Quick entry verification',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Edit goals',exact:true}).click();
  await expect(page.getByLabel('Goal month',{exact:true})).toHaveValue('2026-02');
  await page.getByLabel('Expense limit',{exact:true}).fill('10');await page.getByLabel('Earnings target',{exact:true}).fill('100');
  await page.getByLabel('Investment target',{exact:true}).fill('25');
  await page.getByText('Category expense budgets',{exact:true}).click();
  await page.locator('.category-budget-editor').getByLabel('Groceries',{exact:true}).fill('10');
  await page.getByRole('button',{name:'Save period goals',exact:true}).click();
  await expect(page.getByText('Goals saved for 2026-02.',{exact:true})).toBeVisible();
  await page.getByRole('combobox',{name:'Goal period',exact:true}).selectOption('year');
  await page.getByLabel('Expense limit',{exact:true}).fill('1200');await page.getByRole('button',{name:'Save period goals',exact:true}).click();
  await expect(page.getByText('Goals saved for 2026.',{exact:true})).toBeVisible();
  await page.reload();await page.getByRole('button',{name:'Explore the demo'}).click();
  await page.getByLabel('Month',{exact:true}).selectOption('02');
  await expect(page.getByRole('group',{name:'Expense goal comparison',exact:true})).toContainText('Over limit by PKR 2.50');
  await expect(page.getByRole('group',{name:'Groceries goal comparison',exact:true})).toContainText('Over limit by PKR 2.50');
  await page.getByLabel('Month',{exact:true}).selectOption('all');
  await expect(page.getByRole('group',{name:'Expense goal comparison',exact:true})).toContainText('PKR 1,200.00 planned');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
