import {test,expect} from '@playwright/test';
import {entryAction} from './helpers';

test('goals keep all draft fields across tabs, preserve month across currencies and guard sign-out',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Explore the demo',exact:true}).click();await page.getByRole('button',{name:'Goals',exact:true}).click();
 await page.getByRole('button',{name:/^November 2026/}).click();
 for(const currency of ['USD','PKR']){await page.getByLabel('Goal currency',{exact:true}).selectOption(currency);await expect(page.getByLabel('Goal month',{exact:true})).toHaveValue('2026-11');}
 await page.getByLabel('Earnings target',{exact:true}).fill('200000');await page.getByRole('radio',{name:'Percentages of earnings',exact:true}).check();await page.getByLabel('Savings target percentage',{exact:true}).fill('12');
 await page.getByText('Need help splitting your earnings?',{exact:true}).click();await page.getByLabel('Planning example').selectOption('custom');await page.getByLabel('Cash savings %',{exact:true}).fill('17');
 await page.getByText('Category limits & targets (optional)',{exact:true}).click();await page.locator('.category-budget-editor').getByLabel('Food',{exact:true}).fill('1234');
 await page.getByText('Emergency fund · PKR (optional)',{exact:true}).click();await page.getByLabel('Emergency fund target',{exact:true}).fill('34567');
 for(const tab of ['Overview','Money Log','Categories','Settings']){await page.getByRole('button',{name:tab,exact:true}).click();await page.getByRole('button',{name:'Goals',exact:true}).click();await expect(page.getByLabel('Goal month',{exact:true})).toHaveValue('2026-11');await expect(page.getByLabel('Savings target percentage',{exact:true})).toHaveValue('12');await expect(page.getByLabel('Cash savings %',{exact:true})).toHaveValue('17');await expect(page.getByLabel('Emergency fund target',{exact:true})).toHaveValue('34567');await expect(page.locator('.category-budget-editor').getByLabel('Food',{exact:true})).toHaveValue('1234');}
 await page.getByLabel('Goal currency',{exact:true}).selectOption('USD');await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByLabel('Savings target percentage',{exact:true})).toHaveValue('12');
 await page.getByRole('button',{name:'Exit demo',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByLabel('Emergency fund target',{exact:true})).toHaveValue('34567');
 await page.getByRole('button',{name:'Exit demo',exact:true}).click();await page.getByRole('button',{name:'Discard and exit demo',exact:true}).click();await page.getByRole('button',{name:'Explore the demo',exact:true}).click();await expect(page.getByRole('heading',{name:'Your money, at a glance.',exact:true})).toBeVisible();
});

test('entry currency controls the list and export, while specific deletion can be cancelled',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Explore the demo',exact:true}).click();await page.getByRole('button',{name:'Add expense',exact:true}).click();
 await page.getByLabel('Currency',{exact:true}).selectOption('USD');await page.getByLabel('Amount',{exact:true}).fill('10.25');await page.getByLabel('Category',{exact:true}).selectOption({label:'Groceries'});await page.getByRole('dialog').getByLabel('Note',{exact:false}).fill('Currency filter test');await page.getByRole('button',{name:'Save entry',exact:true}).click();
 await page.getByLabel('Reporting currency',{exact:true}).selectOption('PKR');const summary=await page.locator('.overview-summary').innerText();
 await page.getByLabel('Filter entry currency',{exact:true}).selectOption('USD');await expect(page.locator('.transaction-row')).toHaveCount(1);await expect(page.locator('.overview-summary')).toHaveText(summary);
 await entryAction(page,/^Delete entry Food/);const dialog=page.getByRole('dialog');await expect(dialog).toContainText('USD');await expect(dialog).toContainText('10.25');await expect(dialog).toContainText('Groceries');await expect(dialog).toContainText('Currency filter test');await expect(dialog.getByRole('button',{name:'Delete entry',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('.transaction-row')).toHaveCount(1);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export Excel',exact:true}).click();expect(await (await download).path()).toBeTruthy();
 await page.getByRole('button',{name:'Clear entry filters',exact:true}).click();await expect(page.locator('.transaction-row')).not.toHaveCount(1);await expect(page.locator('.overview-summary')).toHaveText(summary);
});

test('signing out from a mocked admin workspace enters a populated demo',async({page})=>{
 // All provider requests are local fixtures; no production account is signed in or changed.
 const id='11111111-1111-4111-8111-111111111111';const accessToken=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:id,exp:Math.floor(Date.now()/1000)+3600,aud:'authenticated'})).toString('base64url')+'.fixture-only';const profile={user_id:id,currency:'PKR',planning_currency:'PKR',timezone:'UTC',income_target:0,spending_target:0,saving_target:0,investment_target:0,emergency_target:0,emergency_contribution:0};
 await page.route('**/auth/v1/**',async route=>{const path=new URL(route.request().url()).pathname;const user={id,email:'admin-fixture@example.com',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{},created_at:'2026-10-01T00:00:00Z'};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(path.endsWith('/token')?{access_token:accessToken,refresh_token:'fixture-only',expires_in:3600,token_type:'bearer',user}:path.endsWith('/user')?user:{})});});
 await page.route('**/rest/v1/**',async route=>{const path=new URL(route.request().url()).pathname;let data:unknown=[];if(path.endsWith('/profiles'))data=profile;else if(path.endsWith('/is_paisatrace_admin'))data=true;else if(path.endsWith('/paisatrace_admin_overview'))data={total:1,signups_7d:1,signups_30d:1,active_7d:1,active_30d:1,matched:0,users:[]};else if(path.includes('/rpc/'))data=null;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
 await page.goto('/');await page.getByLabel('Email address').fill('admin-fixture@example.com');await page.getByLabel('Password',{exact:true}).fill('fixture-only password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Open admin panel',exact:true}).click();await expect(page.getByRole('heading',{name:'Account administration',exact:true})).toBeVisible();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('button',{name:'Explore the demo',exact:true}).click();await expect(page.getByRole('heading',{name:'Your money, at a glance.',exact:true})).toBeVisible();await expect(page.locator('.overview-summary')).toBeVisible();await expect(page.getByRole('heading',{name:'Account administration',exact:true})).toHaveCount(0);
});
