import { expect, test } from '@playwright/test';

test('optional expense subcategories persist and keep parent totals', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore the demo' }).click();
  await page.getByRole('button', { name: 'Categories', exact: true }).click();
  await page.getByRole('button', { name: 'Add subcategory to Home & bills', exact: true }).click();
  await page.getByLabel('Subcategory name').fill('Utilities');
  await page.getByRole('button', { name: 'Save subcategory', exact: true }).click();
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.getByLabel('Expense category', { exact: true }).selectOption({ label: 'Home & bills' });
  await page.getByLabel('Subcategory (optional)', { exact: true }).selectOption({ label: 'Utilities' });
  await page.getByLabel('Expense amount · PKR', { exact: true }).fill('50');
  await page.getByText('Change date or add a note', { exact: true }).click();
  await page.getByLabel('Expense date', { exact: true }).fill('2026-03-04');
  await page.getByRole('button', { name: 'Save expense', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Where your spending goes' })).toContainText('Utilities');
  await expect(page.getByRole('region', { name: 'Where your spending goes' })).toContainText('PKR 50.00');
  await page.reload();
  await page.getByRole('button', { name: 'Explore the demo' }).click();
  await page.getByRole('button', { name: 'Daily entries', exact: true }).click();
  await page.getByLabel('Month', { exact: true }).selectOption('03');
  await page.getByLabel('Search entries', { exact: true }).fill('Utilities');
  await expect(page.getByRole('row').filter({ hasText: 'Utilities' })).toContainText('Home & bills');
  await page.getByRole('button', { name: 'Edit entry Home & bills 2026-03-04', exact: true }).click();
  await expect(page.getByLabel('Subcategory', { exact: true })).not.toHaveValue('');
  await page.getByLabel('Category', { exact: true }).selectOption({ label: 'Transport' });
  await expect(page.getByLabel('Subcategory', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
