import {expect,test} from '@playwright/test';
test('budget leads overview and recent activity shares its currency scope',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Explore the demo',exact:true}).click();
 const hero=page.locator('.budget-hero');await expect(hero.getByRole('heading',{name:'Budget remaining',exact:true})).toBeVisible();await expect(hero).toContainText('PKR only · All categories');await expect(page.getByRole('progressbar',{name:'Expense budget used'})).toBeVisible();
 await expect(page.getByLabel('Search entries',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toHaveCount(0);
 const before=await hero.innerText();await page.getByRole('button',{name:'Add expense',exact:true}).click();await page.getByLabel('Currency',{exact:true}).selectOption('USD');await page.getByLabel('Category',{exact:true}).selectOption({label:'Food → Groceries'});await page.getByLabel('Amount',{exact:true}).fill('23');await page.getByRole('button',{name:'Save entry',exact:true}).click();
 await page.getByLabel('Reporting currency').selectOption('PKR');await expect(hero).toHaveText(before);await expect(page.locator('.transaction-row').filter({hasText:'USD'})).toHaveCount(0);await page.getByLabel('Reporting currency').selectOption('USD');await expect(page.locator('.transaction-row').filter({hasText:'23.00'})).toHaveCount(1);
 await page.getByRole('button',{name:'Money Log',exact:true}).click();await page.getByLabel('Filter entry currency').selectOption('all');await expect(page.getByLabel('Search entries',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Export Excel',exact:true})).toBeVisible();
});
test('blank goals override defaults while an explicit zero persists independently',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Explore the demo',exact:true}).click();await page.getByRole('button',{name:'Goals',exact:true}).click();await page.getByLabel('Goal month').fill('2026-10');await expect(page.locator('.goal-month-grid')).toHaveCount(0);
 await page.getByLabel('Expense limit',{exact:true}).fill('');await page.getByLabel('Savings target',{exact:true}).fill('0');await page.getByRole('button',{name:'Save monthly goals',exact:true}).click();await expect(page.locator('.goal-saved-status')).toContainText('Saved goals for 2026-10');
 await page.getByRole('button',{name:'Overview',exact:true}).click();await expect(page.locator('.budget-hero')).toContainText('Budget not set');await expect(page.getByRole('progressbar',{name:'Expense budget used'})).toHaveCount(0);
 await page.reload();await page.getByRole('button',{name:'Explore the demo',exact:true}).click();await page.getByRole('button',{name:'Goals',exact:true}).click();await page.getByLabel('Goal month').fill('2026-10');await expect(page.getByLabel('Expense limit',{exact:true})).toHaveValue('');await expect(page.getByLabel('Savings target',{exact:true})).toHaveValue('0.00');
});
test('category search, optional details and save footer fit a shortened phone screen',async({page})=>{
 await page.setViewportSize({width:390,height:500});await page.goto('/');await page.getByRole('button',{name:'Explore the demo',exact:true}).click();await page.getByRole('button',{name:'Add expense',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Search',exact:true}).click();await page.getByLabel('Search category',{exact:true}).fill('groc');await expect(page.getByLabel('Category',{exact:true}).locator('option')).toContainText(['Choose what this is for','Food → Groceries','Other — enter a custom name']);await page.getByLabel('Category',{exact:true}).selectOption({label:'Food → Groceries'});
 await page.getByRole('dialog').getByText('More details',{exact:true}).click();await page.getByLabel('Note (optional)',{exact:true}).fill('Keyboard layout test');const save=await page.getByRole('button',{name:'Save entry',exact:true}).boundingBox();expect(save!.y+save!.height).toBeLessThanOrEqual(500);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();expect(await page.evaluate(()=>document.body.style.position)).toBe('');
});
