import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';
import { userGuide } from './user-guide.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const env = { ...loadEnv(process.argv[2] || 'production', root, 'VITE_'), ...process.env };
const operator = (env.VITE_OPERATOR_NAME || '').trim();
const email = (env.VITE_CONTACT_EMAIL || '').trim();
const site = (env.VITE_SITE_URL || '').trim();
let origin = 'http://127.0.0.1:5173';
if (site) {
  const url = new URL(site);
  if (url.protocol !== 'https:' || url.username || url.password || url.pathname !== '/' || url.search || url.hash) {
    throw new Error('VITE_SITE_URL must be an HTTPS origin, without a path, query, credentials or fragment.');
  }
  origin = url.origin;
}
if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error('VITE_CONTACT_EMAIL must be a valid public email address.');
const reviewed = (env.VITE_PUBLIC_POLICY_REVIEWED ?? env.VITE_POLICY_REVIEWED) === 'true';
const draft = !operator || !email || !site || !reviewed;
const escape = value => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const contact = email ? `Contact ${operator || 'the operator'} at ${email}.` : 'Public operator and contact details have not been set. Real account operation requires these details before launch.';
const status = draft ? 'Prelaunch draft: operator, contact email, final website address and review of actual privacy/terms practices must be completed before public launch.' : 'Published policy. Contact the operator with questions about this service.';
const privacy = [
  ['About this notice', `${status} ${contact} This notice describes PaisaTrace, a manual personal finance tracker. It should be reviewed when deployment providers or data practices change.`],
  ['Information you provide', 'When connected to its backend, PaisaTrace uses your email address and a password for verified sign-in. Supabase manages password verification; passwords are not stored in your financial ledger. The app stores the income, expenses, savings, investment contributions, dates, currencies, categories, notes, targets and preferences you choose to enter. It does not request bank credentials or connect to bank accounts. Avoid adding sensitive information about other people in notes.'],
  ['How information is used', 'Account information supports sign-in and account protection. Signup, verification and sign-in dates, plus a last-active timestamp when the signed-in app is opened, help the operator understand account usage and protect the service. The admin panel shows account emails and these timestamps, not financial records. Financial entries and settings support your private ledger, calculations, reports and Excel exports. Support messages are used to respond to your request. These uses do not involve automated lending decisions or investment recommendations.'],
  ['Service providers', 'Supabase provides authentication and database storage when configured. Vercel serves the website and may process technical request logs, including IP addresses and browser details. Brevo receives your email address and authentication messages to deliver signup verification and password-recovery emails. Returning password sign-in does not send an email. The Supabase database is hosted in Sydney, Australia. Google Fonts serves the current typefaces and receives browser requests. These services may process information in locations outside your country; review their privacy notices and the operator’s selected hosting region.'],
  ['Browser storage and demo data', 'Demo mode uses synthetic data stored in your browser’s local storage. It does not upload demo records to Supabase or sync them across devices. Connected sign-in uses browser storage for the authentication session. Reset demo removes local sample changes; signing out does not delete account records. Necessary storage supports these features. No advertising or analytics SDK is included in the current application.'],
  ['Access, corrections and deletion', 'You can edit or delete entries, change settings and export the selected records to Excel. Categories with history are archived to preserve those records. Account-wide deletion currently requires a request to the operator; it is not an in-app button. The operator must verify account ownership before handling such a request. A restricted admin tool can permanently remove the account and its app records; deletion actions are logged with operator ID, deleted account ID and time, without financial content. Rights and required response periods depend on applicable law.'],
  ['Retention and security', 'Account records are retained while the account is used, until you delete individual records or request account deletion, subject to any applicable legal obligations. Provider logs and any independently retained backups follow the relevant provider or operator retention practices; deleted information may remain there temporarily. Ask the operator about provider log retention and any backups before storing information that depends on a specific deletion deadline. Server-side ownership controls restrict account records to their owner, but no service can promise absolute security. Keep your email account and exported files secure.'],
  ['Changes and questions', `${contact} Material changes to data practices should be reflected here before they take effect. If you have rights under applicable privacy law, you may also contact the appropriate regulator.`],
];
const terms = [
  ['Using PaisaTrace', `${status} ${contact} By using the published service, you agree to these terms. If you do not agree, do not use it. PaisaTrace is a personal finance recording and planning tool.`],
  ['Your account and records', 'Use an email account you control. Protect your inbox, password and recovery links. You are responsible for information you enter, its accuracy, and keeping copies of important records. Use only your own data or data you have permission to record.'],
  ['Planning estimates', 'Totals depend on your entries, currency and filters. Savings and investments show contributions net of withdrawals, not investment returns or a reconciled bank balance. Targets and emergency timelines are editable estimates and do not guarantee outcomes. The service does not provide personalized financial, investment, tax or legal advice.'],
  ['Acceptable use', 'Do not access another person’s records, misuse login emails, upload unlawful content, attempt unauthorized access, or disrupt the service. The operator may restrict access needed to investigate abuse or protect users, subject to applicable law.'],
  ['Availability and cost', 'The current project is intended to operate on free service tiers. Those providers impose quotas and may pause or change services. Availability and uninterrupted operation are not guaranteed. A future paid offering would require separate pricing and terms; this notice does not authorize charges.'],
  ['Exports and ending use', 'You may stop using the app and export your selected records. Deleting entries changes your reports. Removing a category with history archives it. Contact the operator for account-wide deletion; signing out alone does not delete records.'],
  ['Responsibility and legal rights', 'Verify calculations before relying on them for important decisions. To the extent permitted by applicable law, the service is supplied as available, without a promise that it will be error-free or meet every need. Nothing in these terms removes mandatory consumer rights or excludes responsibility that applicable law does not permit the operator to exclude.'],
  ['Changes and contact', `${contact} The operator should update this page when service terms change and give any notice required by applicable law. This service is offered for personal use. Mandatory rights under applicable law continue to apply.`],
];
const css = `:root{font-family:system-ui,sans-serif;color:#25372f;background:#f5f7f6}*{box-sizing:border-box}body{margin:0}main{max-width:850px;margin:auto;padding:32px 24px 60px}a{color:#285943;overflow-wrap:anywhere}nav{display:flex;gap:24px;flex-wrap:wrap;margin:20px 0}nav a{padding:10px 0}h1{font-size:clamp(2rem,6vw,3rem);letter-spacing:-.05em}h2{font-size:1.2rem;margin-top:32px}p{line-height:1.75;overflow-wrap:anywhere}.draft{padding:16px;border:1px solid #d9e7c8;background:#edf5df;border-radius:9px}a:focus-visible{outline:3px solid #77af54;outline-offset:4px}.brand-name{font-weight:700;color:#285943}.start{display:inline-block;min-height:44px;padding:12px 20px;border-radius:8px;background:#162b24;color:white;text-decoration:none}details{padding:14px 0;border-bottom:1px solid #dce4de}summary{cursor:pointer;font-weight:600;min-height:30px}details p{margin-bottom:0}.guide-contents{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px 24px;padding:20px;background:#eaf1e7;border-radius:12px}.guide-contents a{line-height:1.5;min-width:0}.guide-step{padding:20px 0;border-bottom:1px solid #dce4de;scroll-margin-top:20px}.guide-step h2{margin-top:4px;font-size:1.5rem}.step-number{color:#55734f;font-size:.8rem;font-weight:700;letter-spacing:.1em;margin-bottom:0}.guide-step ol{padding-left:24px}.guide-step li{line-height:1.8;padding:6px 0}.guide-note{background:#edf5df;padding:16px;border-radius:8px}.guide-step>a{display:inline-block;padding:10px 0}@media(max-width:600px){.guide-contents{grid-template-columns:1fr}main{padding:24px 18px 50px}}.guide-page main{max-width:1080px}.guide-hero{padding:30px;border-radius:22px;background:#162b24;color:#f4f8ef}.guide-hero .brand-name{color:#c9f478}.guide-hero h1{margin-top:12px}.guide-hero .start{background:#c9f478;color:#162b24;font-weight:700}.guide-path{font-size:.85rem;color:#cfddd2;margin-bottom:0}.guide-demo-note{font-size:.85rem;color:#577164}.guide-page .guide-step{background:white;margin:22px 0;padding:26px;border:1px solid #dce4de;border-radius:18px}.guide-page .guide-note{border-left:3px solid #92ad64}.guide-shot{margin:24px 0 4px;padding:12px;background:#eef3f0;border:1px solid #dce4de;border-radius:16px}.guide-shot>a{display:block;max-width:100%;min-width:0}.guide-shot img{display:block;width:100%;max-width:100%;height:auto;object-fit:contain;border-radius:9px}.guide-shot.phone{max-width:414px;margin-inline:auto}.guide-shot figcaption{font-size:.85rem;line-height:1.5;margin-top:12px;color:#50675a}.guide-page .guide-contents a{text-decoration:none;border-bottom:1px solid #d3dfd0;padding:12px 0}.guide-page .guide-step h2{font-size:clamp(1.3rem,4vw,1.8rem)}@media(max-width:600px){.guide-hero{padding:22px 18px}.guide-page .guide-step{padding:20px 16px}.guide-shot{padding:8px}}footer{margin-top:40px;padding-top:20px;border-top:1px solid #dce4de}`;
const stylesheet = `/site.css?v=${createHash('sha256').update(css).digest('hex').slice(0,12)}`;
const imageVersions = Object.fromEntries(await Promise.all(['overview.jpg','entries.jpg','expense-mobile.jpg','goals-mobile.jpg'].map(async name => [name,createHash('sha256').update(await readFile(new URL('../public/guide-images/'+name,import.meta.url))).digest('hex').slice(0,12)])));
const nav = '<nav aria-label="Public pages"><a href="/">PaisaTrace</a><a href="/about.html">About PaisaTrace</a><a href="/guide.html">User guide</a><a href="/privacy.html">Privacy policy</a><a href="/terms.html">Terms and conditions</a><a href="/third-party-notices.txt">Third-party notices</a></nav>';
const markdown = (title, sections) => `# ${title}\n\n${sections.map(([heading, body]) => `## ${heading}\n\n${body}`).join('\n\n')}\n`;
const html = (slug, title, sections) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · PaisaTrace</title><meta name="robots" content="${draft ? 'noindex, nofollow' : 'index, follow'}"><link rel="stylesheet" href="${stylesheet}"><link rel="icon" href="/favicon.svg"><link rel="alternate" type="text/markdown" href="/${slug}.md"><link rel="describedby" href="/llms.txt">${draft ? '' : `<link rel="canonical" href="${origin}/${slug}.html">`}</head><body><main>${nav}<h1>${title}</h1>${draft ? `<p class="draft">${escape(status)}</p>` : ''}${sections.map(([heading, body]) => `<section><h2>${escape(heading)}</h2><p>${escape(body)}</p></section>`).join('')}<footer><p>Powered by <a href="https://www.hirubix.com/" target="_blank" rel="noopener noreferrer">Rubix Labs</a></p>${nav}</footer></main></body></html>`;
const llms = `# PaisaTrace\n\n> A responsive personal finance tracker with manual entries, multiple currencies, monthly goals and savings planning. Powered by Rubix Labs (https://www.hirubix.com/).\n\n${draft ? 'This deployment is a prelaunch preview. Policy review is still pending.\n\n' : ''}Users can record income, expenses, savings and investment contributions, edit categories, review earnings, spending, savings and investments against monthly goals and category budgets, and export Excel workbooks. The category comparison uses the previous calendar month. Currencies are kept separate. Investment contributions are not returns. Email-and-password sign-in and private persistence require a configured Supabase backend. Demo records are synthetic, local to the browser and do not sync. Account records and login tokens are private and are not public resources.\n\n## Public introduction\n\n- [About PaisaTrace](/about.html): Features, goals, charts and account sign-in.\n\n- [User guide](/guide.html): Step-by-step account setup, entries, monthly goals, reports and troubleshooting.\n\n## Public policies\n\n- [Privacy policy](/privacy.md): Data use, providers, browser storage, retention and contact details.\n- [Terms and conditions](/terms.md): Responsibilities, estimates, acceptable use and service availability.\n\n## Optional\n\n- [Application](/): Sign-in and demo entry point.\n- [Sitemap](/sitemap.xml): Public page URLs when a production origin is configured.\n`;
const urls = draft ? (site ? ['/about.html'] : []) : ['/', '/about.html', '/guide.html', '/privacy.html', '/terms.html'];
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(path => `  <url><loc>${escape(origin + path)}</loc></url>`).join('\n')}\n</urlset>\n`;
const robots = draft ? (site ? `User-agent: *\nAllow: /about.html\nAllow: /site.css\nAllow: /favicon.svg\nDisallow: /\nSitemap: ${origin}/sitemap.xml\n` : 'User-agent: *\nDisallow: /\n') : `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`;
const about = [
  ['Personal finance tracking for everyday life', 'PaisaTrace is a free personal finance tracker for recording everyday spending, income, savings and investment contributions. Choose your preferred supported currency and track each currency separately. It works on phones, tablets and desktops.'],
  ['Record an expense in a few steps', 'Open your dashboard, enter an amount, choose a category or subcategory and save. Subcategories cover expenses, savings and investments, such as Bills, Travel savings or Stocks. Today is already selected. Add a note or a different date when you need one. Record income, savings and investment contributions through Add entry.'],
  ['Understand where your money goes', 'Review your monthly totals, a twelve-month income and expense chart, spending by category and changes from the previous calendar month. Remaining income shows recorded earnings after expenses and net savings and investment contributions. When outgoings exceed earnings, the overview shows the excess; it asks you to record income when none is entered. This is not a bank balance.'],
  ['Plan one month at a time', 'Set an income target, then set expense, savings and investment goals as fixed amounts or percentages of that target. Optional planning examples preview a split for you to confirm and save for the selected month. Add category spending limits and an emergency-fund target. Compare your recorded activity with your goals to see progress and overspending. Goals are optional.'],
  ['Your account, your records', 'Create an account with an email and password, verify your email once and sign in with your password on later visits. Existing email-link users can set a password without creating another ledger. Entries are stored in Supabase with account ownership controls. No bank connection is required.'],
  ['Export and explore', 'Export filtered records to an Excel workbook. Explore the demo before creating an account: its sample data stays in your browser and does not sync to the database. The service currently has no subscription charge.'],
  ['Questions and support', `${contact} Salman Javed operates PaisaTrace. Rubix Labs receives a Powered by credit. Read the privacy notice and terms before creating an account.`],
];
const applicationSchema = JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:'PaisaTrace',url:origin+'/',applicationCategory:'FinanceApplication',operatingSystem:'Web browser',description:'A personal finance tracker for expenses, income, savings, investments and monthly goals.',isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'PKR'},featureList:['Expense and income tracking','Savings and investment contributions','Monthly amount and percentage goals','Category budgets and subcategories','Financial charts','Excel exports']}).replace(/</g,'\\u003c');
const questions = [
 ['Is PaisaTrace free?', 'PaisaTrace currently has no subscription charge and is offered for personal use.'],
 ['Which currencies can I track?', 'PKR is the default. USD, GBP, EUR, AED, JPY and KWD are also supported. Records keep their original currency; amounts are not converted or combined across currencies.'],
 ['Can I plan savings as a percentage of my income?', 'Yes. Enter that month’s earnings target, then choose amount or percentage input for expenses, savings and investments. Saving keeps the calculated amounts as independent monthly goals.'],
 ['Does PaisaTrace connect to my bank?', 'No. You enter your transactions yourself. Recorded totals are an overview of your entries, not a verified bank balance.'],
 ['Can I try it before signing up?', 'Yes. The demo uses sample data stored only in your browser. Create an account for your own records across devices.'],
 ['Does the app provide investment returns?', 'No. It records investment contributions and withdrawals. It does not trade investments or calculate market returns.']
];
const aboutHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PaisaTrace — Free Expense Tracker & Budget Goals</title><meta name="description" content="Track expenses, income, savings and investments in your preferred supported currency. Set monthly budget goals, review financial charts and export Excel with PaisaTrace."><meta name="robots" content="${site ? 'index, follow' : 'noindex, nofollow'}">${site ? `<link rel="canonical" href="${origin}/about.html"><meta property="og:url" content="${origin}/about.html">` : ''}<meta property="og:title" content="PaisaTrace — Your money, a little clearer"><meta property="og:description" content="Expenses, income, savings and investment goals in one place."><meta property="og:type" content="website"><meta property="og:site_name" content="PaisaTrace"><meta name="twitter:card" content="summary_large_image">${site ? `<meta property="og:image" content="${origin}/social-card.png"><meta property="og:image:alt" content="PaisaTrace — Track spending. Plan your month."><meta name="twitter:image" content="${origin}/social-card.png"><script type="application/ld+json">${applicationSchema}</script>` : ''}<link rel="stylesheet" href="${stylesheet}"><link rel="icon" href="/favicon.svg"></head><body><main>${nav}<p>YOUR MONEY. A LITTLE CLEARER.</p><h1>Track your expenses.<br>Make room for your goals.</h1><p class="brand-name">PaisaTrace · Expense tracker & monthly budget planner</p><p>A personal finance dashboard for everyday life.</p><nav aria-label="Get started"><a class="start" href="/">Open PaisaTrace</a><a href="/privacy.html">Read the privacy notice</a></nav>${about.map(([heading,body])=>`<section><h2>${escape(heading)}</h2><p>${escape(body)}</p></section>`).join('')}<section><h2>Frequently asked questions</h2>${questions.map(([q,a])=>`<details><summary>${escape(q)}</summary><p>${escape(a)}</p></details>`).join('')}</section><footer><p>Powered by <a href="https://www.hirubix.com/" target="_blank" rel="noopener noreferrer">Rubix Labs</a></p>${nav}</footer></main></body></html>`;
const guide = userGuide({ origin, draft, nav, contact, escape, stylesheet, imageVersions });
const files = { 'guide.html': guide.html, 'guide.md': guide.md, 'about.html': aboutHtml, 'privacy.html': html('privacy', 'Privacy policy', privacy), 'privacy.md': markdown('Privacy policy', privacy), 'terms.html': html('terms', 'Terms and conditions', terms), 'terms.md': markdown('Terms and conditions', terms), 'llms.txt': llms, 'llm.txt': llms, 'sitemap.xml': sitemap, 'robots.txt': robots, 'site.css': css };
await mkdir(new URL('../public/', import.meta.url), { recursive: true });
for (const [name, value] of Object.entries(files)) await writeFile(new URL(`../public/${name}`, import.meta.url), value, 'utf8');
console.log(draft ? 'Generated public policy drafts; set operator/contact/origin and complete policy review before launch.' : `Generated public policies and sitemap for ${origin}.`);
