import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';

const root = fileURLToPath(new URL('../', import.meta.url));
const env = { ...loadEnv(process.argv[2] || 'production', root, 'VITE_'), ...process.env };
const operator = (env.VITE_OPERATOR_NAME || '').trim();
const email = (env.VITE_CONTACT_EMAIL || '').trim();
const site = (env.VITE_SITE_URL || '').trim();
let origin = 'http://127.0.0.1:5173';
if (site) {
  const url = new URL(site);
  if (url.protocol !== 'https:' || url.username || url.password || url.pathname !== '/' || url.search || url.hash) {
    throw new Error('VITE_SITE_URL must be an HTTPS origin, without a path, query, credentials or fragment.');
  }
  origin = url.origin;
}
if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error('VITE_CONTACT_EMAIL must be a valid public email address.');
const reviewed = env.VITE_POLICY_REVIEWED === 'true';
const draft = !operator || !email || !site || !reviewed;
const escape = value => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const contact = email ? `Contact ${operator || 'the operator'} at ${email}.` : 'Public operator and contact details have not been set. Real account operation requires these details before launch.';
const status = draft ? 'Prelaunch draft: operator, contact email, final website address and review of actual privacy/terms practices must be completed before public launch.' : 'Published policy. Contact the operator with questions about this service.';
const privacy = [
  ['About this notice', `${status} ${contact} This notice describes PaisaTrail, a manual personal finance tracker. It should be reviewed when deployment providers or data practices change.`],
  ['Information you provide', 'When connected to its backend, PaisaTrail uses your email address for verified sign-in and stores the income, expenses, savings, investment contributions, dates, currencies, categories, notes, targets and preferences you choose to enter. It does not request bank credentials or connect to bank accounts. Avoid adding sensitive information about other people in notes.'],
  ['How information is used', 'Account information supports sign-in and account protection. Financial entries and settings support your private ledger, calculations, reports and Excel exports. Support messages are used to respond to your request. These uses do not involve automated lending decisions or investment recommendations.'],
  ['Service providers', 'Supabase provides authentication and database storage when configured. The selected hosting provider, such as Vercel or Cloudflare Pages, serves the website and may process technical request logs, including IP addresses and browser details. The configured email sender receives your email address and login message to deliver sign-in links. Google Fonts serves the current typefaces and receives browser requests. These services may process information in locations outside your country; review their privacy notices and the operator’s selected hosting region.'],
  ['Browser storage and demo data', 'Demo mode uses synthetic data stored in your browser’s local storage. It does not upload demo records to Supabase or sync them across devices. Connected sign-in uses browser storage for the authentication session. Reset demo removes local sample changes; signing out does not delete account records. Necessary storage supports these features. No advertising or analytics SDK is included in the current application.'],
  ['Access, corrections and deletion', 'You can edit or delete entries, change settings and export the selected records to Excel. Categories with history are archived to preserve those records. Account-wide deletion currently requires a request to the operator; it is not an in-app button. The operator must verify account ownership before handling such a request. Rights and required response periods depend on applicable law.'],
  ['Retention and security', 'Account records are retained while the account is used, until you delete individual records or request account deletion, subject to any applicable legal obligations. Provider logs and any independently retained backups follow the relevant provider or operator retention practices; deleted information may remain there temporarily. The operator must document those periods before launch. Server-side ownership controls restrict account records to their owner, but no service can promise absolute security. Keep your email account and exported files secure.'],
  ['Changes and questions', `${contact} Material changes to data practices should be reflected here before they take effect. If you have rights under applicable privacy law, you may also contact the appropriate regulator.`],
];
const terms = [
  ['Using PaisaTrail', `${status} ${contact} By using the published service, you agree to these terms. If you do not agree, do not use it. PaisaTrail is a personal finance recording and planning tool.`],
  ['Your account and records', 'Use an email account you control. Protect your inbox and sign-in links. You are responsible for information you enter, its accuracy, and keeping copies of important records. Use only your own data or data you have permission to record.'],
  ['Planning estimates', 'Totals depend on your entries, currency and filters. Savings and investments show contributions net of withdrawals, not investment returns or a reconciled bank balance. Targets and emergency timelines are editable estimates and do not guarantee outcomes. The service does not provide personalized financial, investment, tax or legal advice.'],
  ['Acceptable use', 'Do not access another person’s records, misuse login emails, upload unlawful content, attempt unauthorized access, or disrupt the service. The operator may restrict access needed to investigate abuse or protect users, subject to applicable law.'],
  ['Availability and cost', 'The current project is intended to operate on free service tiers. Those providers impose quotas and may pause or change services. Availability and uninterrupted operation are not guaranteed. A future paid offering would require separate pricing and terms; this notice does not authorize charges.'],
  ['Exports and ending use', 'You may stop using the app and export your selected records. Deleting entries changes your reports. Removing a category with history archives it. Contact the operator for account-wide deletion; signing out alone does not delete records.'],
  ['Responsibility and legal rights', 'Verify calculations before relying on them for important decisions. To the extent permitted by applicable law, the service is supplied as available, without a promise that it will be error-free or meet every need. Nothing in these terms removes mandatory consumer rights or excludes responsibility that applicable law does not permit the operator to exclude.'],
  ['Changes and contact', `${contact} The operator should update this page when service terms change and give any notice required by applicable law. No governing jurisdiction is specified in this prelaunch draft; it must be reviewed for the operator’s actual location and audience.`],
];
const css = `:root{font-family:system-ui,sans-serif;color:#25372f;background:#f5f7f6}*{box-sizing:border-box}body{margin:0}main{max-width:850px;margin:auto;padding:32px 24px 60px}a{color:#285943;overflow-wrap:anywhere}nav{display:flex;gap:24px;flex-wrap:wrap;margin:20px 0}nav a{padding:10px 0}h1{font-size:clamp(2rem,6vw,3rem);letter-spacing:-.05em}h2{font-size:1.2rem;margin-top:32px}p{line-height:1.75;overflow-wrap:anywhere}.draft{padding:16px;border:1px solid #d9e7c8;background:#edf5df;border-radius:9px}a:focus-visible{outline:3px solid #77af54;outline-offset:4px}footer{margin-top:40px;padding-top:20px;border-top:1px solid #dce4de}`;
const nav = '<nav aria-label="Public pages"><a href="/">PaisaTrail</a><a href="/privacy.html">Privacy policy</a><a href="/terms.html">Terms and conditions</a><a href="/third-party-notices.txt">Third-party notices</a></nav>';
const markdown = (title, sections) => `# ${title}\n\n${sections.map(([heading, body]) => `## ${heading}\n\n${body}`).join('\n\n')}\n`;
const html = (slug, title, sections) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · PaisaTrail</title><meta name="robots" content="${draft ? 'noindex, nofollow' : 'index, follow'}"><link rel="stylesheet" href="/site.css"><link rel="icon" href="/favicon.svg"><link rel="alternate" type="text/markdown" href="/${slug}.md"><link rel="describedby" href="/llms.txt">${draft ? '' : `<link rel="canonical" href="${origin}/${slug}.html">`}</head><body><main>${nav}<h1>${title}</h1>${draft ? `<p class="draft">${escape(status)}</p>` : ''}${sections.map(([heading, body]) => `<section><h2>${escape(heading)}</h2><p>${escape(body)}</p></section>`).join('')}<footer><p>Powered by <a href="https://www.hirubix.com/" target="_blank" rel="noopener noreferrer">Hirubix</a></p>${nav}</footer></main></body></html>`;
const llms = `# PaisaTrail\n\n> A responsive personal finance tracker launching for Pakistan, with manual entries, PKR defaults, monthly/yearly goals and savings planning. Powered by Hirubix (https://www.hirubix.com/).\n\n${draft ? 'This deployment is a prelaunch preview. Public operator details have not yet been completed.\n\n' : ''}Users can record income, expenses, savings and investment contributions, edit categories, review earnings, spending, savings and investments against monthly/yearly goals and category budgets, and export Excel workbooks. The category comparison uses the previous calendar month. Currencies are kept separate. Investment contributions are not returns. Optional email-link sign-in and private persistence require a configured Supabase backend. Demo records are synthetic, local to the browser and do not sync. Account records and login tokens are private and are not public resources.\n\n## Public policies\n\n- [Privacy policy](/privacy.md): Data use, providers, browser storage, retention and contact details.\n- [Terms and conditions](/terms.md): Responsibilities, estimates, acceptable use and service availability.\n\n## Optional\n\n- [Application](/): Sign-in and demo entry point.\n- [Sitemap](/sitemap.xml): Public page URLs when a production origin is configured.\n`;
const urls = draft ? [] : ['/', '/privacy.html', '/terms.html'];
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(path => `  <url><loc>${escape(origin + path)}</loc></url>`).join('\n')}\n</urlset>\n`;
const robots = draft ? 'User-agent: *\nDisallow: /\n' : `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`;
const files = { 'privacy.html': html('privacy', 'Privacy policy', privacy), 'privacy.md': markdown('Privacy policy', privacy), 'terms.html': html('terms', 'Terms and conditions', terms), 'terms.md': markdown('Terms and conditions', terms), 'llms.txt': llms, 'llm.txt': llms, 'sitemap.xml': sitemap, 'robots.txt': robots, 'site.css': css };
await mkdir(new URL('../public/', import.meta.url), { recursive: true });
for (const [name, value] of Object.entries(files)) await writeFile(new URL(`../public/${name}`, import.meta.url), value, 'utf8');
console.log(draft ? 'Generated public policy drafts; set operator/contact/origin and complete policy review before launch.' : `Generated public policies and sitemap for ${origin}.`);
