import { useEffect, useRef, useState } from 'react';
import { supabase } from './api';
import Modal from './Modal';
type Account={id:string;email:string;created_at:string;email_confirmed_at:string|null;last_sign_in_at:string|null;last_active_at:string|null;is_admin:boolean};
type Overview={total:number;signups_7d:number;signups_30d:number;active_7d:number;active_30d:number;matched:number;users:Account[]};
const date=(value:string|null)=>value?new Date(value).toLocaleString():'Not yet';
export default function AdminPanel(){
 const [data,setData]=useState<Overview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0),[target,setTarget]=useState<Account|null>(null),[email,setEmail]=useState(''),[deleting,setDeleting]=useState(false),[notice,setNotice]=useState('');
 const pending=useRef(false);
 useEffect(()=>{let alive=true;setBusy(true);setError('');setData(null);supabase!.rpc('paisatrace_admin_overview',{p_search:query,p_offset:offset}).then(({data,error})=>{if(!alive)return;if(error)setError(error.message);else setData(data as Overview);setBusy(false);});return()=>{alive=false;};},[query,offset,revision]);
 async function remove(){if(!target||pending.current)return;pending.current=true;setDeleting(true);setError('');try{const r=await supabase!.rpc('paisatrace_admin_delete_user',{p_user_id:target.id,p_confirm_email:email});if(r.error)throw r.error;setTarget(null);setEmail('');setNotice('Account and app records deleted. Provider backups and logs follow their own retention.');setOffset(0);setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{pending.current=false;setDeleting(false);}}
 return <section className="panel admin-panel"><div className="panel-head"><div><h2>Admin panel</h2><p>Account totals and recent use. Activity means the app was opened while signed in; it is not proof of a transaction.</p></div><button className="button secondary" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Refresh</button></div>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Loading accounts…</p>}{data&&<><div className="admin-metrics">{[['Total accounts',data.total],['Signups · 7 days',data.signups_7d],['Signups · 30 days',data.signups_30d],['Active · 7 days',data.active_7d],['Active · 30 days',data.active_30d]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="small muted">Counts include existing accounts and exclude deleted accounts. Activity tracking starts with this update. Earlier usage is unavailable. Dates use your device timezone. Financial records are not shown here.</p></>}
 <form className="admin-search" onSubmit={e=>{e.preventDefault();setOffset(0);setQuery(search.trim());}}><label>Find an account<input type="search" value={search} maxLength={254} onChange={e=>setSearch(e.target.value)} placeholder="Email address"/></label><button className="button secondary" disabled={busy}>Search</button></form>
 {data&&<><p>{data.matched} matching accounts</p><div className="admin-users">{data.users.map(account=><article key={account.id} className="admin-user"><h3>{account.email||'No email'} {account.is_admin&&<span className="small">· Admin</span>}</h3><dl><div><dt>Signed up</dt><dd>{date(account.created_at)}</dd></div><div><dt>Verified</dt><dd>{account.email_confirmed_at?'Yes':'No'}</dd></div><div><dt>Last sign-in</dt><dd>{date(account.last_sign_in_at)}</dd></div><div><dt>Last active</dt><dd>{date(account.last_active_at)}</dd></div></dl><button className="button danger" disabled={account.is_admin||!account.email} onClick={()=>{setTarget(account);setEmail('');setError('');}}>Delete account</button></article>)}</div><div className="admin-pagination"><button className="button secondary" disabled={busy||offset===0} onClick={()=>setOffset(v=>Math.max(0,v-25))}>Previous</button><span>{data.matched?offset+1:0}–{Math.min(offset+25,data.matched)}</span><button className="button secondary" disabled={busy||offset+25>=data.matched} onClick={()=>setOffset(v=>v+25)}>Next</button></div></>}
 {target&&<Modal title="Permanently delete this account?" close={()=>{if(!deleting)setTarget(null);}}><p><strong>{target.email}</strong></p><p>This permanently removes the account and its entries, categories, goals and settings. It cannot be undone in the app. Export requests should be handled before deletion. Provider backups/logs may retain data temporarily.</p><p>Deletion requires a sign-in within the last 15 minutes. Admin accounts are protected.</p>{error&&<p role="alert" className="form-error">{error}</p>}<form className="stack-form" onSubmit={e=>{e.preventDefault();void remove();}}><label>Type the account email<input type="email" required autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)} disabled={deleting}/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={deleting} onClick={()=>setTarget(null)}>Cancel</button><button className="button danger" disabled={deleting||email.trim().toLowerCase()!==target.email.toLowerCase()}>{deleting?'Deleting…':'Permanently delete account'}</button></div></form></Modal>}
 </section>;
}
