import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, Download, Leaf, LogOut, Mail, Pencil, PiggyBank, Plus, Search, Settings, ShieldCheck, Tags, Trash2, TrendingUp, Wallet, X } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { configured, supabase, loadLedger, saveEntry, deleteEntry, saveCategory, removeCategory, saveProfile } from './api';
import { newDemo, persistDemo, readDemo } from './demo';
import CategoryComparison from './CategoryComparison';
import MonthlyGoals from './MonthlyGoals';
import { dateLabel, emergency, filtered, inputAmount, kindLabels, money, parseAmount, today, totals, validDate } from './finance';
import { currencies, kinds, type Category, type Currency, type Entry, type Filter, type Kind, type Ledger, type Profile } from './types';
const monthNames = Array.from({ length: 12 }, (_, i) => new Date(2000, i, 1).toLocaleString('en', { month: 'long' }));
const icons = { expense: Wallet, saving: PiggyBank, investment: TrendingUp, income: ArrowDownLeft };

function Modal({ title, children, close }: { title: string; children: ReactNode; close: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const old = document.activeElement as HTMLElement; ref.current?.showModal(); return () => old?.focus(); }, []);
  return <dialog ref={ref} onCancel={e => { e.preventDefault(); close(); }} onClick={e => { if (e.target === e.currentTarget) close(); }} aria-labelledby="dialog-title"><div className="modal-content"><div className="modal-head"><h2 id="dialog-title">{title}</h2><button className="icon-button" onClick={close} aria-label="Close dialog"><X size={20}/></button></div>{children}</div></dialog>;
}
function ErrorMessage({ message }: { message: string }) { return message ? <p className="form-error" role="alert">{message}</p> : null; }

export default function App() {
  const [user, setUser] = useState<User | null>(null); const [authLoading, setAuthLoading] = useState(configured); const [demo, setDemo] = useState(false);
  const identity = useRef<string | null>(null);
  const [ledger, setLedger] = useState<Ledger | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [tab, setTab] = useState('overview'); const [filter, setFilter] = useState<Filter>({ year: today().slice(0, 4), month: today().slice(5, 7), category: 'all' }); const [search, setSearch] = useState('');
  const [entryModal, setEntryModal] = useState<Entry | 'new' | null>(null); const [categoryModal, setCategoryModal] = useState<Category | 'new' | null>(null); const [confirmation, setConfirmation] = useState<{ title: string; message: string; action: () => Promise<void> } | null>(null);
  useEffect(() => {
    if (!supabase) return;
    let alive = true;
    function updateIdentity(next: User | null) { if (!alive) return; if (identity.current !== (next?.id ?? null)) { identity.current = next?.id ?? null; setLedger(null); setDemo(false); } setUser(next); setAuthLoading(false); }
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => updateIdentity(session?.user ?? null));
    supabase.auth.getSession().then(({ data, error }) => { updateIdentity(data.session?.user ?? null); if (alive && error) setError(error.message); }).catch(e => { if (alive) { setError(String(e)); setAuthLoading(false); } });
    const callbackError = new URLSearchParams(location.hash.slice(1)).get('error_description'); if (callbackError) { setError(callbackError.replace(/\+/g, ' ')); history.replaceState(null, '', location.pathname); }
    return () => { alive = false; subscription.unsubscribe(); };
  }, []);
  useEffect(() => {
    if (demo) { setLedger(readDemo()); return; }
    if (!user) { setLedger(null); return; }
    let alive = true; setBusy(true); setError('');
    loadLedger(user.id).then(v => { if (alive) { setLedger(v); const date = today(v.profile.timezone); setFilter({ year: date.slice(0, 4), month: date.slice(5, 7), category: 'all' }); } }).catch(e => { if (alive) setError(e.message); }).finally(() => { if (alive) setBusy(false); });
    return () => { alive = false; };
  }, [user?.id, demo]);
  useEffect(() => { if (!notice) return; const t = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(t); }, [notice]);
  async function mutate(work: () => Promise<void>, next: Ledger, success: string) {
    setBusy(true); setError('');
    try { if (demo) { persistDemo(next); setLedger(next); } else { await work(); setLedger(await loadLedger(user!.id)); } setNotice(success); }
    catch (e) { throw new Error(e instanceof Error ? e.message : 'Something went wrong. Please try again.'); }
    finally { setBusy(false); }
  }
  async function signOut() { setError(''); if (demo) { setDemo(false); setLedger(null); return; } const r = await supabase?.auth.signOut(); if (r?.error) setError(r.error.message); else { setUser(null); setLedger(null); } }
  if (authLoading) return <div className="loading"><Leaf/><p>Opening your ledger…</p></div>;
  if (!demo && !user) return <Login enterDemo={() => { setError(''); setDemo(true); }} authError={error}/>;
  if (!ledger) return <div className="loading"><Leaf/><h2>{busy ? 'Opening your ledger…' : 'Could not open your ledger'}</h2><ErrorMessage message={error}/><button className="button" onClick={() => location.reload()}>Try again</button><button className="text-button" onClick={signOut}>Sign out</button></div>;
  const current = filtered(ledger.entries, filter); const currency = ledger.profile.currency; const values = totals(ledger, current, currency); const fund = emergency(ledger);
  const visible = current.filter(e => { const c = ledger.categories.find(c => c.id === e.category_id)!; return `${e.notes} ${c.name} ${kindLabels[c.kind]}`.toLowerCase().includes(search.toLowerCase()); });
  const years = [...new Set([today(ledger.profile.timezone).slice(0, 4), filter.year, ...ledger.entries.map(e => e.date.slice(0, 4))])].filter(y => y !== 'all').sort().reverse();
  const period = filter.year === 'all' ? 'All history' : filter.month === 'all' ? filter.year : `${monthNames[Number(filter.month) - 1]} ${filter.year}`;
  const left = values.income - values.expense - values.saving - values.investment;
  async function exportExcel() { setBusy(true); setError(''); try { const exportLedger = demo ? ledger! : await loadLedger(user!.id); const { downloadWorkbook } = await import('./export'); await downloadWorkbook(exportLedger, filtered(exportLedger.entries, filter).filter(e => { const c = exportLedger.categories.find(c => c.id === e.category_id)!; return `${e.notes} ${c.name} ${kindLabels[c.kind]}`.toLowerCase().includes(search.toLowerCase()); }), filter); setNotice('Excel export downloaded.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function confirmDelete(e: Entry) { setConfirmation({ title: 'Delete this entry?', message: 'This removes the entry and updates your reports.', action: async () => { await mutate(() => deleteEntry(e.id, ledger!.profile.user_id), { ...ledger!, entries: ledger!.entries.filter(x => x.id !== e.id) }, 'Entry deleted.'); } }); }
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#" onClick={e => { e.preventDefault(); setTab('overview'); }}><span className="brand-mark"><Leaf size={23}/></span>Paisa<span className="brand-light">Trail</span></a><div className="workspace-label">YOUR PERSONAL FINANCES</div><nav aria-label="Main navigation">{[{ id: 'overview', name: 'Overview', Icon: BarChart3 }, { id: 'entries', name: 'Daily entries', Icon: CalendarDays }, { id: 'categories', name: 'Categories', Icon: Tags }, { id: 'plan', name: 'Savings plan', Icon: PiggyBank }, { id: 'settings', name: 'Settings', Icon: Settings }].map(({ id, name, Icon }) => <button key={id} className={tab === id ? 'nav-item active' : 'nav-item'} onClick={() => { setTab(id); setSearch(''); }} aria-label={name} title={name} aria-current={tab === id ? 'page' : undefined}><Icon size={19}/><span>{name}</span></button>)}</nav><div className="sidebar-bottom"><div className="private-note"><ShieldCheck size={18}/><span>{demo ? 'Demo workspace' : 'Your own private space'}</span></div><div className="account"><div className="avatar">{demo ? 'D' : (user?.email?.[0] ?? 'U').toUpperCase()}</div><div><strong>{demo ? 'Demo account' : 'My account'}</strong><span title={user?.email}>{demo ? 'Sample data only' : user?.email}</span></div><button className="icon-button" aria-label={demo ? 'Exit demo' : 'Sign out'} onClick={signOut}><LogOut size={18}/></button></div></div></aside>
    <main className="main">
      {demo && <div className="demo-banner"><span><strong>Demo mode</strong> · Sample data, saved only in this browser. Use sign-in for private data across devices.</span><button onClick={() => setConfirmation({ title: 'Reset demo?', message: 'Your changes to the sample data will be removed.', action: async () => { const fresh = newDemo(); persistDemo(fresh); setLedger(fresh); } })}>Reset demo</button></div>}
      <header className="page-header"><div><p className="eyebrow">A LITTLE CLARITY, EVERY DAY</p><h1>{tab === 'overview' ? 'Your money, at a glance.' : tab === 'entries' ? 'Daily entries' : tab === 'categories' ? 'Your categories' : tab === 'plan' ? 'Your savings plan' : 'Settings'}</h1><p className="subtitle">{tab === 'overview' ? 'Spend thoughtfully. Make room for what matters.' : tab === 'entries' ? 'The small things add up. Keep them all in one place.' : tab === 'categories' ? 'Organize your money in a way that makes sense to you.' : tab === 'plan' ? 'A simple plan for your next steps.' : 'Make this space yours.'}</p></div><div className="header-actions">{(tab === 'overview' || tab === 'entries') && <><button className="button secondary" onClick={exportExcel} disabled={busy}><Download size={17}/>Export Excel</button><button className="button" onClick={() => setEntryModal('new')} disabled={busy}><Plus size={19}/>Add entry</button></>}{tab === 'categories' && <button className="button" onClick={() => setCategoryModal('new')} disabled={busy}><Plus size={19}/>Add category</button>}</div></header>
      <ErrorMessage message={error}/>{notice && <div className="toast" role="status"><Check size={17}/>{notice}</div>}
      {(tab === 'overview' || tab === 'entries') && <><div className="period-bar"><div className="period-title"><CalendarDays size={19}/><strong>{period}</strong></div><div className="period-controls"><label><span className="sr-only">Year</span><select aria-label="Year" value={filter.year} onChange={e => setFilter({ ...filter, year: e.target.value, month: e.target.value === 'all' ? 'all' : filter.month })}><option value="all">All years</option>{years.map(y => <option key={y}>{y}</option>)}</select></label><label><span className="sr-only">Month</span><select aria-label="Month" value={filter.month} disabled={filter.year === 'all'} onChange={e => setFilter({ ...filter, month: e.target.value })}><option value="all">Full year</option>{monthNames.map((m, i) => <option key={m} value={String(i + 1).padStart(2, '0')}>{m}</option>)}</select></label><span className="currency-label">{currency}</span></div></div>
      <div className="stats-grid">{kinds.map(kind => { const Icon = icons[kind]; return <section className={`stat-card ${kind}`} key={kind}><div className="stat-label"><span>{kindLabels[kind]}</span><span className="stat-icon"><Icon size={18}/></span></div><strong>{money(values[kind], currency)}</strong><span className="stat-caption">{kind === 'income' ? 'Money coming in' : kind === 'expense' ? 'Day-to-day spending' : kind === 'saving' ? 'Set aside, net of withdrawals' : 'Contributions, net of withdrawals'}</span></section>; })}</div>
      <div className="cashflow-line"><span>Left to allocate <strong className={left < 0 ? 'negative' : ''}>{money(left, currency)}</strong></span><span>Income − expenses − savings − investments</span></div>{current.some(e => e.currency !== currency) && <p className="info-note">Totals show {currency} only. Entries and Excel exports keep each currency separate.</p>}
      {tab === 'overview' && <div className="insights-grid"><CategoryComparison ledger={ledger} currency={currency} filter={filter}/><section className="panel emergency-panel"><div className="panel-head"><h2>Emergency fund</h2><span className="small-icon"><ShieldCheck size={18}/></span></div><p>A cushion for the unexpected.</p><strong className="fund-amount">{money(fund.funded, currency)}</strong><span className="muted">{fund.target > 0 ? `of ${money(fund.target, currency)} target` : 'Set a target in your savings plan'}</span><div className="progress"><span style={{ width: `${fund.percent}%` }}/></div><div className="fund-foot"><span>{fund.target > 0 ? `${Math.round(fund.percent)}% funded` : 'No target yet'}</span><button className="text-button" onClick={() => setTab('plan')}>View plan</button></div></section></div>}
      {tab === 'overview' && <MonthlyGoals ledger={ledger} filter={filter} edit={() => setTab('plan')}/>}
      <section className="panel entries-panel"><div className="panel-head"><div><h2>{tab === 'overview' ? 'Recent entries' : 'All entries'}<span className="count">{visible.length}</span></h2><p>{period}{filter.category !== 'all' ? ` · ${ledger.categories.find(c => c.id === filter.category)?.name}` : ''}</p></div><div className="entry-filters"><label className="search-field"><Search size={16}/><input aria-label="Search entries" placeholder="Search entries" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="Filter category" value={filter.category} onChange={e => setFilter({ ...filter, category: e.target.value })}><option value="all">All categories</option>{ledger.categories.map(c => <option key={c.id} value={c.id}>{c.name}{c.archived ? ' (archived)' : ''}</option>)}</select></div></div><EntryTable entries={tab === 'overview' ? visible.slice(0, 8) : visible} ledger={ledger} edit={setEntryModal} remove={confirmDelete} busy={busy}/>{visible.length === 0 && <div className="empty"><CalendarDays size={30}/><h3>{ledger.entries.length ? 'No entries match this view' : 'A fresh start for your money'}</h3><p>{ledger.entries.length ? 'Try a different month, category, or search.' : 'Add your first expense, saving, or investment.'}</p><button className="button secondary" onClick={() => setEntryModal('new')}><Plus size={17}/>Add entry</button></div>}{tab === 'overview' && visible.length > 8 && <button className="view-all" onClick={() => setTab('entries')}>View all {visible.length} entries</button>}</section><p className="page-foot">A clearer picture, one entry at a time.</p></>}
      {tab === 'categories' && <><div className="category-grid">{kinds.map(kind => <section className="panel" key={kind}><div className="panel-head"><h2>{kindLabels[kind]}</h2><span className={`kind-icon ${kind}`}>{(() => { const Icon = icons[kind]; return <Icon size={19}/>; })()}</span></div>{ledger.categories.filter(c => c.kind === kind).map(c => <div className={`category-row ${c.archived ? 'archived' : ''}`} key={c.id}><div><strong>{c.name}</strong><div className="category-tags">{c.archived && <span>Archived</span>}{c.essential && <span>Essential</span>}{c.emergency && <span>Emergency fund</span>}</div></div><div className="row-actions"><button className="icon-button" aria-label={`Edit ${c.name}`} disabled={busy} onClick={() => setCategoryModal(c)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${c.name}`} disabled={busy || c.archived} onClick={() => { const used = ledger.entries.some(e => e.category_id === c.id); setConfirmation({ title: used ? 'Archive this category?' : 'Delete this category?', message: used ? 'This category has entries. Archiving hides it from new entries and keeps your history and totals intact.' : 'This unused category will be removed.', action: async () => { await mutate(() => removeCategory(c, used), { ...ledger, categories: used ? ledger.categories.map(x => x.id === c.id ? { ...x, archived: true } : x) : ledger.categories.filter(x => x.id !== c.id) }, used ? 'Category archived. History preserved.' : 'Category deleted.'); } }); }}><Trash2 size={16}/></button></div></div>)}{!ledger.categories.some(c => c.kind === kind) && <p className="muted">No categories yet.</p>}</section>)}</div><p className="info-note">Renaming keeps the category type. Categories with entries are archived when removed, so your history stays intact.</p></>}
      {tab === 'plan' && <Plan ledger={ledger} busy={busy} save={async profile => mutate(() => saveProfile(profile), { ...ledger, profile }, 'Savings plan updated.')}/>}
      {tab === 'settings' && <SettingsForm ledger={ledger} busy={busy} logout={signOut} save={async profile => mutate(() => saveProfile(profile), { ...ledger, profile }, 'Settings updated.')}/>}
      <PublicLinks/>
    </main>
    {entryModal && <EntryForm ledger={ledger} entry={entryModal} busy={busy} close={() => setEntryModal(null)} save={async entry => { await mutate(() => saveEntry(entry, entryModal !== 'new'), { ...ledger, entries: entryModal === 'new' ? [...ledger.entries, entry] : ledger.entries.map(x => x.id === entry.id ? entry : x) }, entryModal === 'new' ? 'Entry added.' : 'Entry updated.'); setEntryModal(null); }}/ >}
    {categoryModal && <CategoryForm category={categoryModal} ledger={ledger} busy={busy} close={() => setCategoryModal(null)} save={async category => { await mutate(() => saveCategory(category, categoryModal !== 'new'), { ...ledger, categories: categoryModal === 'new' ? [...ledger.categories, category] : ledger.categories.map(x => x.id === category.id ? category : x) }, 'Category saved.'); setCategoryModal(null); }}/ >}
    {confirmation && <Confirm title={confirmation.title} message={confirmation.message} busy={busy} close={() => setConfirmation(null)} action={async () => { await confirmation.action(); setConfirmation(null); }}/ >}
  </div>;
}

function Login({ enterDemo, authError }: { enterDemo: () => void; authError: string }) {
  const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [cooldown, setCooldown] = useState(0);
  useEffect(() => { if (!cooldown) return; const timer = setTimeout(() => setCooldown(v => v - 1), 1000); return () => clearTimeout(timer); }, [cooldown]);
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); if (!supabase) { setError('Email sign-in is not connected yet. You can explore the demo below.'); return; } setBusy(true); try { const { error } = await supabase.auth.signInWithOtp({ email: email.trim(), options: { emailRedirectTo: location.origin + '/', shouldCreateUser: true } }); if (error) throw error; setSent(true); setCooldown(60); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <main className="login-shell"><section className="login-story"><a className="brand" href="/"><span className="brand-mark"><Leaf size={25}/></span>Paisa<span className="brand-light">Trail</span></a><div><p className="eyebrow">YOUR MONEY. A LITTLE CLEARER.</p><h1>Small habits.<br/>A stronger<br/><em>tomorrow.</em></h1><p>Keep track of what comes in, what goes out, and what you’re putting away.</p><div className="login-tags"><span><Wallet size={17}/>Expenses</span><span><PiggyBank size={17}/>Savings</span><span><TrendingUp size={17}/>Investments</span></div></div><p className="login-bottom">One simple space for your everyday finances.</p></section><section className="login-main"><div className="login-card"><div className="login-symbol"><Leaf size={30}/></div><h2>{sent ? 'Check your inbox' : 'Welcome to your ledger.'}</h2><p>{sent ? `We sent a sign-in link to ${email}. Open it to continue. If it hasn't arrived, check your spam folder.` : 'Enter your email. We’ll send you a secure sign-in link. No password to remember.'}</p><form onSubmit={submit}><label htmlFor="email">Email address</label><div className="email-field"><Mail size={18}/><input id="email" type="email" autoComplete="email" placeholder="you@example.com" required value={email} onChange={e => { setEmail(e.target.value); setSent(false); }}/></div><ErrorMessage message={error || authError}/><button className="button login-submit" disabled={busy || cooldown > 0}>{busy ? 'Sending link…' : cooldown ? `Resend in ${cooldown}s` : sent ? 'Resend sign-in link' : 'Send sign-in link'}</button></form><div className="login-divider"><span>or take a look around</span></div><button className="button secondary login-submit" onClick={enterDemo}>Explore the demo</button><p className="login-privacy"><ShieldCheck size={15}/>Your finances stay in your own account.</p>{!configured && <p className="setup-note">Preview available · Email sign-in will be enabled after setup.</p>}<PublicLinks/></div></section></main>;
}
function EntryTable({ entries, ledger, edit, remove, busy }: { entries: Entry[]; ledger: Ledger; edit: (e: Entry) => void; remove: (e: Entry) => void; busy: boolean }) {
  return <div className="table-wrap"><table><thead><tr><th>Entry</th><th>Date</th><th>Type</th><th className="amount-cell">Amount</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{entries.map(e => { const c = ledger.categories.find(c => c.id === e.category_id)!; const Icon = icons[c.kind]; return <tr key={e.id}><td><div className="entry-description"><span className={`kind-icon ${c.kind}`}><Icon size={18}/></span><div><strong>{c.name}{c.archived ? ' · archived' : ''}</strong><span>{e.notes || (e.withdrawal ? 'Withdrawal' : 'No note')}</span><span className="mobile-entry-date">{dateLabel(e.date)}</span></div></div></td><td className="date-cell">{dateLabel(e.date)}</td><td><span className={`badge ${c.kind}`}>{e.withdrawal ? 'Withdrawal' : kindLabels[c.kind]}</span></td><td className="amount-cell"><strong>{e.withdrawal ? '−' : ''}{money(e.amount_minor, e.currency)}</strong></td><td><div className="row-actions"><button className="icon-button" aria-label={`Edit entry ${c.name} ${e.date}`} disabled={busy} onClick={() => edit(e)}><Pencil size={15}/></button><button className="icon-button" aria-label={`Delete entry ${c.name} ${e.date}`} disabled={busy} onClick={() => remove(e)}><Trash2 size={15}/></button></div></td></tr>; })}</tbody></table></div>;
}
function EntryForm({ ledger, entry, busy, close, save }: { ledger: Ledger; entry: Entry | 'new'; busy: boolean; close: () => void; save: (e: Entry) => Promise<void> }) {
  const existing = entry === 'new' ? null : entry; const [kind, setKind] = useState<Kind>(existing ? ledger.categories.find(c => c.id === existing.category_id)!.kind : 'expense');
  const [category, setCategory] = useState(existing?.category_id ?? ledger.categories.find(c => c.kind === 'expense' && !c.archived)?.id ?? ''); const [date, setDate] = useState(existing?.date ?? today(ledger.profile.timezone)); const [currency, setCurrency] = useState<Currency>(existing?.currency ?? ledger.profile.currency); const [amount, setAmount] = useState(existing ? inputAmount(existing.amount_minor, existing.currency) : ''); const [notes, setNotes] = useState(existing?.notes ?? ''); const [withdrawal, setWithdrawal] = useState(existing?.withdrawal ?? false); const [error, setError] = useState('');
  const options = ledger.categories.filter(c => c.kind === kind && (!c.archived || c.id === existing?.category_id));
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); try { if (!validDate(date)) throw new Error('Choose a valid date between 1900 and 2100.'); if (!category) throw new Error('Add a category for this type first.'); const selected = ledger.categories.find(c => c.id === category)!; if (selected.archived && category !== existing?.category_id) throw new Error('Choose an active category.'); await save({ id: existing?.id ?? crypto.randomUUID(), user_id: ledger.profile.user_id, category_id: category, date, amount_minor: parseAmount(amount, currency), currency, notes: notes.trim(), withdrawal: (kind === 'saving' || kind === 'investment') && withdrawal }); } catch (e) { setError((e as Error).message); } }
  return <Modal title={existing ? 'Edit entry' : 'Add an entry'} close={() => { if (!busy) close(); }}><form onSubmit={submit} className="stack-form"><fieldset className="kind-picker"><legend className="sr-only">Entry type</legend>{kinds.map(k => <label key={k} className={kind === k ? 'selected' : ''}><input type="radio" name="kind" value={k} checked={kind === k} onChange={() => { setKind(k); setCategory(ledger.categories.find(c => c.kind === k && !c.archived)?.id ?? ''); setWithdrawal(false); }}/>{kindLabels[k]}</label>)}</fieldset><div className="form-grid"><label>Amount<input autoFocus inputMode="decimal" placeholder="0.00" required value={amount} onChange={e => setAmount(e.target.value)}/></label><label>Currency<select value={currency} onChange={e => setCurrency(e.target.value as Currency)}>{currencies.map(c => <option key={c}>{c}</option>)}</select></label></div><label>Category<select aria-label="Category" required value={category} onChange={e => setCategory(e.target.value)}><option value="" disabled>Choose a category</option>{options.map(c => <option key={c.id} value={c.id}>{c.name}{c.archived ? ' (archived)' : ''}</option>)}</select></label><label>Date<input type="date" min="1900-01-01" max="2100-12-31" required value={date} onChange={e => setDate(e.target.value)}/></label>{(kind === 'saving' || kind === 'investment') && <label>Movement<select value={withdrawal ? 'withdrawal' : 'contribution'} onChange={e => setWithdrawal(e.target.value === 'withdrawal')}><option value="contribution">Contribution</option><option value="withdrawal">Withdrawal</option></select></label>}<label>Note <span className="muted">(optional)</span><textarea rows={2} maxLength={500} placeholder="What was it for?" value={notes} onChange={e => setNotes(e.target.value)}/></label><ErrorMessage message={error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={close} disabled={busy}>Cancel</button><button className="button" disabled={busy}>{busy ? 'Saving…' : 'Save entry'}</button></div></form></Modal>;
}
function CategoryForm({ ledger, category, busy, close, save }: { ledger: Ledger; category: Category | 'new'; busy: boolean; close: () => void; save: (c: Category) => Promise<void> }) {
  const existing = category === 'new' ? null : category; const [name, setName] = useState(existing?.name ?? ''); const [kind, setKind] = useState<Kind>(existing?.kind ?? 'expense'); const [essential, setEssential] = useState(existing?.essential ?? false); const [isEmergency, setEmergency] = useState(existing?.emergency ?? false); const [archived, setArchived] = useState(existing?.archived ?? false); const [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); try { if (!name.trim()) throw new Error('Enter a category name.'); if (ledger.categories.some(c => c.id !== existing?.id && c.kind === kind && c.name.toLowerCase() === name.trim().toLowerCase())) throw new Error('A category with this name already exists in this type.'); await save({ id: existing?.id ?? crypto.randomUUID(), user_id: ledger.profile.user_id, name: name.trim(), kind, essential: kind === 'expense' && essential, emergency: kind === 'saving' && isEmergency, archived }); } catch (e) { setError((e as Error).message); } }
  return <Modal title={existing ? 'Edit category' : 'Add a category'} close={() => { if (!busy) close(); }}><form className="stack-form" onSubmit={submit}><label>Name<input autoFocus required maxLength={60} placeholder="e.g. Groceries" value={name} onChange={e => setName(e.target.value)}/></label><label>Type<select value={kind} disabled={!!existing} onChange={e => setKind(e.target.value as Kind)}>{kinds.map(k => <option key={k} value={k}>{kindLabels[k]}</option>)}</select></label>{kind === 'expense' && <label className="checkbox-label"><input type="checkbox" checked={essential} onChange={e => setEssential(e.target.checked)}/>Essential expense</label>}{kind === 'saving' && <label className="checkbox-label"><input type="checkbox" checked={isEmergency} onChange={e => setEmergency(e.target.checked)}/>Count toward my emergency fund</label>}{existing?.archived && <label className="checkbox-label"><input type="checkbox" checked={!archived} onChange={e => setArchived(!e.target.checked)}/>Restore for new entries</label>}<ErrorMessage message={error}/><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={close}>Cancel</button><button className="button" disabled={busy}>{busy ? 'Saving…' : 'Save category'}</button></div></form></Modal>;
}
function Confirm({ title, message, busy, close, action }: { title: string; message: string; busy: boolean; close: () => void; action: () => Promise<void> }) {
  const [error, setError] = useState(''); return <Modal title={title} close={() => { if (!busy) close(); }}><p>{message}</p><ErrorMessage message={error}/><div className="modal-actions"><button className="button secondary" onClick={close} disabled={busy}>Cancel</button><button className="button danger" disabled={busy} onClick={async () => { try { await action(); } catch (e) { setError((e as Error).message); } }}>{busy ? 'Updating…' : 'Confirm'}</button></div></Modal>;
}
function Plan({ ledger, busy, save }: { ledger: Ledger; busy: boolean; save: (profile: Profile) => Promise<void> }) {
  const p = ledger.profile; const currency = p.currency; const [form, setForm] = useState({ income_target: inputAmount(p.income_target, currency), spending_target: inputAmount(p.spending_target, currency), saving_target: inputAmount(p.saving_target, currency), investment_target: inputAmount(p.investment_target, currency), emergency_target: inputAmount(p.emergency_target, currency), emergency_contribution: inputAmount(p.emergency_contribution, currency) }); const [error, setError] = useState(''); const fund = emergency(ledger);
  const planned = p.income_target - p.spending_target - p.investment_target - p.saving_target;
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); try { const parsed = Object.fromEntries(Object.entries(form).map(([key, v]) => [key, parseAmount(v, currency, true)])); if (parsed.emergency_contribution > parsed.saving_target) throw new Error('The emergency contribution must fit within your total monthly savings target.'); await save({ ...p, ...parsed }); } catch (e) { setError((e as Error).message); } }
  return <div className="plan-grid"><section className="panel plan-form"><h2>Make room for your goals</h2><p className="muted">Optional monthly targets in {currency}. Total savings includes your emergency contribution; these are planning estimates.</p><form className="stack-form" onSubmit={submit}>{([{ key: 'income_target', label: 'Expected monthly income' }, { key: 'spending_target', label: 'Monthly spending limit' }, { key: 'saving_target', label: 'Monthly savings target (including emergency)' }, { key: 'investment_target', label: 'Monthly investment contribution' }, { key: 'emergency_target', label: 'Emergency fund target' }, { key: 'emergency_contribution', label: 'Monthly emergency contribution' }] as const).map(({ key, label }) => <label key={key}>{label}<input inputMode="decimal" required value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })}/></label>)}<ErrorMessage message={error}/><button className="button" disabled={busy}>{busy ? 'Saving…' : 'Save plan'}</button></form></section><div className="plan-summary"><section className="panel"><h2>Emergency fund progress</h2><strong className="fund-amount">{money(fund.funded, currency)}</strong><p className="muted">{fund.target > 0 ? `Target: ${money(fund.target, currency)}` : 'Set a target to see your progress.'}</p><div className="progress"><span style={{ width: `${fund.percent}%` }}/></div><p>{fund.target <= 0 ? 'No target configured yet.' : fund.months === 0 ? 'Your target is reached.' : fund.months === null ? `${money(fund.gap, currency)} to go. Set a monthly contribution to estimate your timeline.` : `${money(fund.gap, currency)} to go · about ${fund.months} monthly contributions.`}</p><p className="small muted">Estimate assumes fixed contributions and no withdrawals or interest. Mark a savings category as “emergency fund” to count its entries here.</p></section><section className="panel"><h2>Monthly room to spare</h2><strong className={`fund-amount ${planned < 0 ? 'negative' : ''}`}>{money(planned, currency)}</strong><p>{planned < 0 ? 'Your targets exceed your expected income. Adjust them to close the gap.' : 'Expected income after your spending limit, total savings target, and investment target.'}</p><p className="small muted">Emergency contributions are included within total savings. Unrecorded commitments are not included. Investment contributions are not investment returns.</p></section></div></div>;
}
function SettingsForm({ ledger, busy, save, logout }: { ledger: Ledger; busy: boolean; logout: () => Promise<void>; save: (p: Profile) => Promise<void> }) {
  const [currency, setCurrency] = useState(ledger.profile.currency); const [timezone, setTimezone] = useState(ledger.profile.timezone); const [error, setError] = useState(''); const zones = [...new Set([ledger.profile.timezone, Intl.DateTimeFormat().resolvedOptions().timeZone, 'UTC', 'Asia/Karachi', 'Asia/Dubai', 'Asia/Kolkata', 'Europe/London', 'Europe/Paris', 'America/New_York', 'America/Los_Angeles', 'Australia/Sydney'])];
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); try { await save({ ...ledger.profile, currency, timezone, ...(currency !== ledger.profile.currency ? { income_target: 0, spending_target: 0, saving_target: 0, investment_target: 0, emergency_target: 0, emergency_contribution: 0 } : {}) }); } catch (e) { setError((e as Error).message); } }
  return <section className="panel settings-panel"><h2>Your preferences</h2><form className="stack-form" onSubmit={submit}><label>Display & default currency<select value={currency} onChange={e => setCurrency(e.target.value as Currency)}>{currencies.map(c => <option key={c}>{c}</option>)}</select></label><p className="small muted">Existing entries keep their original currency. Changing currency resets planning targets to zero; it does not convert money.</p><label>Timezone<select value={timezone} onChange={e => setTimezone(e.target.value)}>{zones.map(z => <option key={z}>{z}</option>)}</select></label><p className="small muted">Used for today’s date and your default reporting month. Existing entry dates stay as recorded.</p><ErrorMessage message={error}/><button className="button" disabled={busy}>{busy ? 'Saving…' : 'Save settings'}</button><button type="button" className="button secondary" disabled={busy} onClick={logout}><LogOut size={17}/>Sign out</button></form></section>;
}

function PublicLinks() { return <footer className="public-links" aria-label="Legal and public information"><a href="/privacy.html">Privacy policy</a><a href="/terms.html">Terms and conditions</a><a href="/sitemap.xml">Sitemap</a><a href="/llms.txt">llms.txt</a></footer>; }
