import PlanComparisonChart from './PlanComparisonChart';
import {useState} from 'react';
import {budgetReport,varianceLabel,type BudgetRow} from './budgetReport';
import {money} from './finance';
import {kindLabels,type Filter,type Kind,type Ledger} from './types';
export type DrillScope={kind:Kind;categoryId?:string;subcategoryId?:string};
function Progress({row,peak,currency}:{row:BudgetRow;peak:number;currency:Ledger['profile']['currency']}){
 const over=row.kind==='expense'&&row.remaining!==null&&row.remaining<0;
 return <div className={`budget-chart-bars ${over?'over':''}`} role="img" aria-label={`${row.name}: ${row.target===null?'plan not set':'planned '+money(row.target,currency)}, actual ${money(row.actual,currency)}`}><div className="planned-bar"><i style={{width:`${row.target===null?0:Math.max(0,row.target)/peak*100}%`}}/></div><div className="actual-bar"><i style={{width:`${Math.max(0,row.actual)/peak*100}%`}}/></div></div>;
}
export default function BudgetDashboard({ledger,filter,drill,editGoals}:{ledger:Ledger;filter:Filter;drill:(scope:DrillScope)=>void;editGoals:()=>void}) {
 const [kind,setKind]=useState<Kind>('expense'),[all,setAll]=useState(false),[expanded,setExpanded]=useState<string|null>(null),[threshold,setThreshold]=useState(80);
 const report=budgetReport(ledger,filter),currency=ledger.profile.currency;
 const rows=report.categories.filter(r=>r.kind===kind);const shown=all?rows:rows.slice(0,5);
 const categoryPeak=Math.max(1,...rows.flatMap(r=>[Math.max(0,r.actual),r.target??0]));
 return <div className="dashboard-charts budget-dashboard">
 <section className="panel main-budget-panel" aria-labelledby="main-budget-heading"><div className="panel-head"><div><h2 id="main-budget-heading">Plan vs. actual</h2><p>Monthly plans · {currency} · selected period</p></div><button className="text-button" onClick={editGoals}>Edit goals</button></div><div className="budget-legend"><span><i className="planned-key"/>Planned</span><span><i className="actual-key"/>Actual</span></div>
 {report.main.every(r=>r.count===0)&&<p className="small muted">No recorded activity for this period.</p>}<PlanComparisonChart rows={report.main} currency={currency} select={kind=>{setKind(kind);setAll(false);setExpanded(null);}}/><div className="main-budget-rows">{report.main.map(row=><button key={row.id} className={`main-budget-row ${row.kind} ${kind===row.kind?'selected':''}`} aria-pressed={kind===row.kind} onClick={()=>{setKind(row.kind);setAll(false);setExpanded(null);}}><div className="budget-row-heading"><strong>{row.name}</strong><span>{row.percent===null?row.target===0?'Zero target':row.target===null?'Not set':'—':`${row.percent.toFixed(1)}%`}</span></div><div className="budget-row-amounts"><span>Plan <b>{row.target===null?'Not set':money(row.target,currency)}</b></span><span>Actual <b>{money(row.actual,currency)}</b></span></div><small className={row.kind==='expense'&&row.remaining!==null&&row.remaining<0?'negative':''}>{row.remaining!==null?money(Math.abs(row.remaining),currency)+' · ':''}{varianceLabel(row)}</small><small className="budget-source">{row.source}</small></button>)}</div>
 <details className="chart-data"><summary>Contribution details</summary>{report.main.filter(r=>r.kind!=='expense').map(r=><p key={r.id}>{r.name}: {money(r.contribution,currency)} contributed − {money(r.withdrawal,currency)} withdrawn = {money(r.actual,currency)} net. {r.kind==='investment'?'Market value is not tracked. Received dividends or returns can be recorded separately as income.':''}</p>)}<p>Custom date ranges prorate each monthly plan by covered calendar days. Year views add monthly plans; they do not use historical annual goals. Missing monthly plans show Not set.</p></details></section>
 <section className="panel spending-panel category-budget-panel" aria-labelledby="category-budget-heading"><div className="panel-head"><div><h2 id="category-budget-heading">{kindLabels[kind]} breakdown</h2><p>Highest {kind==='expense'?'spending':'net contributions'} first · {currency}</p></div><button className="text-button" onClick={()=>drill({kind})}>View records</button></div>
 {kind==='expense'&&<label className="budget-warning-control">Warn at<select aria-label="Budget warning threshold" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}><option value={80}>80% of limit</option><option value={90}>90% of limit</option><option value={100}>100% of limit</option></select></label>}
 <div className="category-budget-list spending-list">{shown.map(row=>{const children=report.subcategories.filter(s=>s.parentId===row.id);const direct=row.actual-children.reduce((v,s)=>v+s.actual,0);const over=kind==='expense'&&row.remaining!==null&&row.remaining<0;const warning=kind==='expense'&&row.target!==null&&row.percent!==null&&row.percent>=threshold;return <article className="category-budget-item" key={row.id}><div className="budget-row-heading"><button className="text-button category-drill" onClick={()=>drill({kind,categoryId:row.id})}>{row.name}{row.archived?' · archived':''}</button><strong>{money(row.actual,currency)}</strong></div><Progress row={row} peak={categoryPeak} currency={currency}/><div className="category-budget-meta"><span>Plan {row.target===null?'Not set':money(row.target,currency)}</span><span>{row.percent===null?row.target===0?'Zero limit':'—':`${row.percent.toFixed(1)}%`}</span></div><small className={over?'negative':warning?'budget-near':''}>{row.remaining===null?kind==='expense'?'No category limit':'No category target':`${money(Math.abs(row.remaining),currency)} · ${varianceLabel(row)}`}{warning&&!over?' · Limit nearly used':''}</small>
 {children.length>0&&<><button className="text-button subcategory-toggle" aria-expanded={expanded===row.id} onClick={()=>setExpanded(expanded===row.id?null:row.id)}>{expanded===row.id?'Hide':'Show'} subcategories</button>{expanded===row.id&&<div className="budget-subcategories">{children.map(s=><button key={s.id} onClick={()=>drill({kind,categoryId:row.id,subcategoryId:s.id})}><span>{s.name}{s.archived?' · archived':''}</span><strong>{money(s.actual,currency)}</strong></button>)}{row.count>children.reduce((v,s)=>v+s.count,0)&&<div className="direct-category-total"><span>No subcategory</span><strong>{money(direct,currency)}</strong></div>}<small>Parent total includes these records once. Limits apply to the parent category.</small></div>}</>}
 </article>;})}</div>
 {!rows.length&&<div className="comparison-empty">No {kindLabels[kind].toLowerCase()} categories or records in this view.</div>}
 {rows.length>5&&<button className="view-all" onClick={()=>setAll(!all)}>{all?'Show top 5':`View all ${rows.length} categories`}</button>}
 </section></div>;
}
