import {useState} from 'react';
import {cashFlowSlices,ringPath,type FlowSlice} from './flowChartData';
import {money} from './finance';
import type {Filter,Ledger} from './types';
import type {DrillScope} from './BudgetDashboard';
const colors=['#4b795e','#82a571','#a47450','#597f9f','#9b688a','#b49644','#708b86','#856f54'];
export default function CashFlowChart({ledger,filter,drill}:{ledger:Ledger;filter:Filter;drill:(scope:DrillScope)=>void}){
 const [kind,setKind]=useState<'expense'|'income'>('expense'),[expanded,setExpanded]=useState<string|null>(null);const {rows,total}=cashFlowSlices(ledger,filter,kind);let angle=-Math.PI/2;
 const arcs=rows.map((row,i)=>{const start=angle;angle+=row.amount/total*Math.PI*2;let childAngle=start;return {row,start,end:angle,color:colors[i%colors.length],children:row.children.map(child=>{const childStart=childAngle;childAngle+=child.amount/total*Math.PI*2;return {child,start:childStart,end:childAngle};})};});
 function view(row:FlowSlice){drill({kind,categoryId:row.categoryId,subcategoryId:row.subcategoryId??(row.id.startsWith('direct-')?'__none__':undefined)});}
 return <section className="panel cash-flow-panel" aria-labelledby="cash-flow-heading"><div className="panel-head"><div><h2 id="cash-flow-heading">See where your money goes</h2><p>All categories · {ledger.profile.currency} · selected period</p></div><div className="flow-type-picker" aria-label="Breakdown type">{(['expense','income'] as const).map(k=><button key={k} className={kind===k?'selected':''} aria-pressed={kind===k} onClick={()=>{setKind(k);setExpanded(null);}}>{k==='expense'?'Expenses':'Income'}</button>)}</div></div>
 <div className="cash-flow-layout"><div className="flow-visual"><strong className="flow-total">{money(total,ledger.profile.currency)}</strong><span className="small muted">{kind==='expense'?'Recorded spending':'Recorded income'}</span>{total>0?<svg viewBox="0 0 320 320" className="flow-ring" role="group" aria-label={`${kind==='expense'?'Expenses':'Income'} by category and subcategory`}>{arcs.map(({row,start,end,color,children})=><g key={row.id}><path d={ringPath(start,end,81,116)} fill={color} role="button" tabIndex={0} aria-label={`${row.name}: ${money(row.amount,ledger.profile.currency)}. View records`} onClick={()=>view(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();view(row);}}}><title>{row.name}: {money(row.amount,ledger.profile.currency)}</title></path>{children.map(({child,start,end},i)=><path key={child.id} d={ringPath(start,end,121,150)} fill={color} fillOpacity={0.55+0.4*((i%3)/2)} role="button" tabIndex={0} aria-label={`${row.name}, ${child.name}: ${money(child.amount,ledger.profile.currency)}. View records`} onClick={()=>view(child)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();view(child);}}}><title>{row.name} → {child.name}: {money(child.amount,ledger.profile.currency)}</title></path>)}</g>)}<text x="160" y="151" textAnchor="middle">{kind==='expense'?'Expenses':'Income'}</text><text x="160" y="177" textAnchor="middle" className="flow-center-small">Selected period</text></svg>:<div className="flow-empty">No {kind==='expense'?'expenses':'income'} recorded in this period.</div>}<p className="small muted">Inner ring: categories · outer ring: subcategories. Select a slice or a name to view records.</p></div>
 <div className="flow-legend">{arcs.map(({row,color})=><div className="flow-legend-family" key={row.id}><button className="flow-category" onClick={()=>view(row)}><i style={{background:color}}/><span>{row.name}</span><strong>{money(row.amount,ledger.profile.currency)}<small>{(row.amount/total*100).toFixed(1)}%</small></strong></button>{row.children.some(child=>!!child.subcategoryId)&&<><button className="text-button" aria-expanded={expanded===row.id} onClick={()=>setExpanded(expanded===row.id?null:row.id)}>{expanded===row.id?'Hide':'Show'} details for {row.name}</button>{expanded===row.id&&<div className="flow-children">{row.children.map(child=><button key={child.id} onClick={()=>view(child)}><span>{child.name}</span><strong>{money(child.amount,ledger.profile.currency)}</strong></button>)}</div>}</>}</div>)}</div></div></section>;
}
