import {useState} from 'react';
import {Pencil,Plus,Search,Trash2} from 'lucide-react';
import {budgetReport,varianceLabel} from './budgetReport';
import {money} from './finance';
import {kinds,kindLabels,type Category,type Filter,type Kind,type Ledger,type Subcategory} from './types';
export default function CategoriesPanel({ledger,filter,busy,addCategory,editCategory,editSubcategory,removeCategory,removeSubcategory}:{ledger:Ledger;filter:Filter;busy:boolean;addCategory:()=>void;editCategory:(c:Category)=>void;editSubcategory:(s:Subcategory|{category_id:string})=>void;removeCategory:(c:Category)=>void;removeSubcategory:(s:Subcategory)=>void}){
 const [search,setSearch]=useState(''),[kind,setKind]=useState<Kind|'all'>('all'),[status,setStatus]=useState('active');
 const report=budgetReport(ledger,filter),currency=ledger.profile.currency;
 const query=search.trim().toLowerCase();
 const match=(c:Category)=> (status==='all'||(status==='active'?!c.archived:c.archived)) && (c.name.toLowerCase().includes(query)||(ledger.subcategories??[]).some(s=>s.category_id===c.id&&s.name.toLowerCase().includes(query)));
 return <section className="category-workspace"><div className="category-toolbar"><label className="search-field"><Search size={16}/><input aria-label="Search categories" placeholder="Find a category or subcategory" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Category type filter" value={kind} onChange={e=>setKind(e.target.value as Kind|'all')}><option value="all">All types</option>{kinds.map(k=><option key={k} value={k}>{kindLabels[k]}</option>)}</select><select aria-label="Category status filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All statuses</option></select><button className="button" disabled={busy} onClick={addCategory}><Plus size={17}/>Add category</button></div>
 <div className="compact-category-groups">{kinds.filter(k=>kind==='all'||k===kind).map(k=>{const categories=ledger.categories.filter(c=>c.kind===k&&match(c));return <section className="panel compact-category-group" key={k}><div className="panel-head"><h2>{kindLabels[k]}</h2><span className="count">{categories.length}</span></div>{categories.map(c=>{const row=report.categories.find(r=>r.id===c.id),children=(ledger.subcategories??[]).filter(s=>s.category_id===c.id);return <div className={`compact-category-family ${c.archived?'archived':''}`} key={c.id}><div className="compact-category-row"><div className="category-name"><strong>{c.name}</strong><small>{c.archived?'Archived · ':''}{c.essential?'Essential · ':''}{c.emergency?'Emergency · ':''}{children.length} subcategories</small></div><div className="category-financials"><strong>Actual {money(row?.actual??0,currency)}</strong><small>Plan {row?.target==null?'Not set':money(row.target,currency)}</small>{row?.remaining!=null&&<small className={k==='expense'&&row.remaining<0?'negative':''}>{money(Math.abs(row.remaining),currency)} · {varianceLabel(row)}</small>}</div><div className="row-actions"><button className="icon-button" aria-label={`Edit ${c.name}`} disabled={busy} onClick={()=>editCategory(c)}><Pencil size={16}/><span className="sr-only">Edit</span></button><button className="icon-button" aria-label={`Delete ${c.name}`} disabled={busy||c.archived} onClick={()=>removeCategory(c)}><Trash2 size={16}/><span className="sr-only">Delete</span></button></div></div>{k!=='income'&&<details className="compact-subcategories" open={query&&children.some(s=>s.name.toLowerCase().includes(query))?true:undefined}><summary>Subcategories & details</summary><div className="subcategory-list">{children.filter(s=>!query||c.name.toLowerCase().includes(query)||s.name.toLowerCase().includes(query)).map(s=><div className="subcategory-row" key={s.id}><span>{s.name}{s.archived?' · archived':''}</span><div className="row-actions"><button className="icon-button" aria-label={`Edit ${s.name} in ${c.name}`} disabled={busy} onClick={()=>editSubcategory(s)}><Pencil size={15}/></button><button className="icon-button" aria-label={`Delete ${s.name} in ${c.name}`} disabled={busy||s.archived} onClick={()=>removeSubcategory(s)}><Trash2 size={15}/></button></div></div>)}{!c.archived&&<button className="text-button add-subcategory" disabled={busy} onClick={()=>editSubcategory({category_id:c.id})}><Plus size={15}/>Add subcategory to {c.name}</button>}</div></details>}</div>;})}{!categories.length&&<p className="muted small category-empty">No matching categories.</p>}</section>;})}</div><p className="small muted">Selected period · {currency} only. Linked categories are archived to preserve history. Set category limits and contribution targets in Goals.</p>
 </section>;
}
