import {useState} from 'react';
import {filtered,money,totals} from './finance';
import {reportMonths} from './budgetReport';
import type {Filter,Ledger} from './types';
export default function DashboardDetails({ledger,filter,selectMonth}:{ledger:Ledger;filter:Filter;selectMonth:(year:string,month:string)=>void}){
 const [active,setActive]=useState<string|null>(null),[offset,setOffset]=useState(0);
 const currency=ledger.profile.currency,entries=filtered(ledger.entries,{...filter,category:'all',currency});
 const selectedMonths=reportMonths(filter).map(m=>m.month);
 const months=selectedMonths.length?selectedMonths:[...new Set(entries.map(e=>e.date.slice(0,7)))].sort();
 const rows=months.map(month=>({month,...totals(ledger,entries.filter(e=>e.date.startsWith(month)),currency)}));
 const maxOffset=Math.max(0,rows.length-12),first=Math.min(offset,maxOffset),shown=rows.slice(first,first+12),peak=Math.max(1,...rows.flatMap(r=>[r.income,r.expense]));const selected=rows.find(r=>r.month===active);
 return <section className="panel trend-panel" aria-labelledby="trend-heading"><div className="panel-head"><h2 id="trend-heading">Income & spending</h2><span className="small muted">Selected period · {currency}</span></div><div className="trend-legend"><span><i style={{background:'#285943'}}/>Income</span><span><i style={{background:'#cf975a'}}/>Expenses</span></div>{!rows.length?<p className="comparison-empty">No activity in this period.</p>:<><div className="trend-readout" aria-live="polite">{selected?<><strong>{selected.month}</strong><span>Income {money(selected.income,currency)}</span><span>Expenses {money(selected.expense,currency)}</span></>:<span>Focus or hover for exact amounts; select a month to open it.</span>}</div><div className="trend-chart">{shown.map(row=><button className="trend-month" key={row.month} onFocus={()=>setActive(row.month)} onBlur={()=>setActive(null)} onMouseEnter={()=>setActive(row.month)} onMouseLeave={()=>setActive(null)} onClick={()=>selectMonth(row.month.slice(0,4),row.month.slice(5))} aria-label={`${row.month}: income ${money(row.income,currency)}, expenses ${money(row.expense,currency)}. Show this month.`}><span className="trend-bars" aria-hidden="true"><i style={{height:`${row.income/peak*100}%`,background:'#285943'}}/><i style={{height:`${row.expense/peak*100}%`,background:'#cf975a'}}/></span><span>{row.month.slice(5)}<small>{row.month.slice(0,4)}</small></span></button>)}</div>{rows.length>12&&<div className="trend-pagination"><button className="text-button" disabled={first===0} onClick={()=>setOffset(Math.max(0,first-12))}>Previous months</button><span>{first+1}–{Math.min(first+12,rows.length)} of {rows.length}</span><button className="text-button" disabled={first>=maxOffset} onClick={()=>setOffset(Math.min(maxOffset,first+12))}>Next months</button></div>}<details className="chart-data"><summary>View chart data</summary><div className="table-wrap"><table><thead><tr><th>Month</th><th>Income</th><th>Expenses</th></tr></thead><tbody>{rows.map(r=><tr key={r.month}><td>{r.month}</td><td>{money(r.income,currency)}</td><td>{money(r.expense,currency)}</td></tr>)}</tbody></table></div></details></>}</section>;
}
