import { useEffect, useState, type FormEvent } from 'react';
import { supabase } from './api';
import BrandMark from './BrandMark';
export default function EmailCallback({callback,accepted,cancel}:{callback:{access_token:string;refresh_token:string;recovery:boolean};accepted:()=>void;cancel:()=>void}){
 const [email,setEmail]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;if(!supabase){setError('Account sign-in is not connected.');return;}supabase.auth.getUser(callback.access_token).then(({data,error})=>{if(!alive)return;if(error||!data.user?.email)setError('This link is invalid or expired. Request a new email link.');else setEmail(data.user.email);});return()=>{alive=false;};},[callback.access_token]);
 async function submit(event:FormEvent){event.preventDefault();if(busy||!email||confirmation.trim().toLowerCase()!==email.toLowerCase())return;setBusy(true);setError('');try{const r=await supabase!.auth.setSession({access_token:callback.access_token,refresh_token:callback.refresh_token});if(r.error)throw r.error;accepted();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="recovery-shell"><BrandMark/><section className="panel settings-panel"><h1>Confirm your account</h1><p>This email link belongs to <strong>{email||'an account being checked…'}</strong>.</p><p>Continue only if this is your email and you requested this verification or password-recovery link. This prevents an unexpected link from opening someone else’s ledger.</p>{error&&<p className="form-error" role="alert">{error}</p>}{email&&<form className="stack-form" onSubmit={submit}><label>Your email address<input type="email" required autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="button" disabled={busy||confirmation.trim().toLowerCase()!==email.toLowerCase()}>{busy?'Opening account…':callback.recovery?'Continue to password recovery':'Continue to my account'}</button></form>}<button className="text-button" disabled={busy} onClick={cancel}>Cancel this link</button></section></main>;
}
