import { useRef, useState, type FormEvent } from 'react';
import { Plus } from 'lucide-react';
import { parseAmount, today, validDate } from './finance';
import type { Entry, Ledger } from './types';
export default function QuickExpense({ ledger, busy, save, more }: {ledger:Ledger;busy:boolean;save:(entry:Entry)=>Promise<void>;more:()=>void}) {
  const categories=ledger.categories.filter(c=>c.kind==='expense'&&!c.archived);
  const [amount,setAmount]=useState(''); const [category,setCategory]=useState(categories[0]?.id??''); const [subcategory,setSubcategory]=useState('');
  const subcategories=(ledger.subcategories??[]).filter(s=>s.category_id===category&&!s.archived);
  const [date,setDate]=useState(today(ledger.profile.timezone));const [notes,setNotes]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');
  const amountRef=useRef<HTMLInputElement>(null); const pending=useRef(false);
  async function submit(e:FormEvent){e.preventDefault();if(pending.current)return;pending.current=true;setError('');setSuccess('');try{const selected=categories.find(c=>c.id===category);if(!selected)throw new Error('Choose an active expense category.');if(subcategory&&!subcategories.some(s=>s.id===subcategory))throw new Error('Choose a subcategory in this category.');if(!validDate(date))throw new Error('Choose a valid date between 1900 and 2100.');await save({id:crypto.randomUUID(),user_id:ledger.profile.user_id,category_id:category,subcategory_id:subcategory||null,date,currency:ledger.profile.currency,amount_minor:parseAmount(amount,ledger.profile.currency),notes:notes.trim(),withdrawal:false});setAmount('');setNotes('');setSuccess('Expense saved.');amountRef.current?.focus();}catch(e){setError((e as Error).message);}finally{pending.current=false;}}
  return <section className="panel quick-expense" aria-labelledby="quick-expense-heading"><div className="panel-head"><div><h2 id="quick-expense-heading">Add an expense</h2><p>Amount, category, save. Today is already selected.</p></div><button type="button" className="text-button" onClick={more}>Income, savings or investment</button></div><form onSubmit={submit}><div className="quick-expense-fields"><label>Expense amount · {ledger.profile.currency}<input ref={amountRef} inputMode="decimal" placeholder="0.00" required value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);setSuccess('');}}/></label><label>Expense category<select required value={category} disabled={busy} onChange={e=>{setCategory(e.target.value);setSubcategory('');}}><option value="" disabled>Choose a category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{subcategories.length>0&&<label>Subcategory <span className="muted">(optional)</span><select value={subcategory} disabled={busy} onChange={e=>setSubcategory(e.target.value)}><option value="">No subcategory</option>{subcategories.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button className="button" disabled={busy||!categories.length}><Plus size={18}/>{busy?'Saving…':'Save expense'}</button></div><details className="quick-expense-options"><summary>Change date or add a note</summary><div className="form-grid"><label>Expense date<input type="date" required min="1900-01-01" max="2100-12-31" disabled={busy} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Expense note (optional)<input maxLength={500} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What was it for?"/></label></div></details>{!categories.length&&<p className="info-note">Add an expense category in Categories to start recording.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p role="status" className="goal-status favorable">{success}</p>}</form></section>;
}
