import { useRef, useState, type FormEvent } from 'react';
import { Plus } from 'lucide-react';
import { parseAmount, today, validDate } from './finance';
import type { Entry, Kind, Ledger } from './types';
import AmountWords from './AmountWords';
import { expenseChoices } from './expenseChoices';
export default function QuickExpense({ ledger, busy, save, more }: {ledger:Ledger;busy:boolean;save:(entry:Entry)=>Promise<void>;more:(kind:Kind)=>void}) {
  const choices=expenseChoices(ledger);
  const [amount,setAmount]=useState(''); const [choice,setChoice]=useState(choices[0]?.value??'');
  const [date,setDate]=useState(today(ledger.profile.timezone));const [notes,setNotes]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');
  const amountRef=useRef<HTMLInputElement>(null); const pending=useRef(false);
  async function submit(e:FormEvent){e.preventDefault();if(pending.current)return;pending.current=true;setError('');setSuccess('');try{const selected=choices.find(c=>c.value===choice);if(!selected)throw new Error('Choose an expense category or subcategory.');if(!validDate(date))throw new Error('Choose a valid date between 1900 and 2100.');await save({id:crypto.randomUUID(),user_id:ledger.profile.user_id,category_id:selected.categoryId,subcategory_id:selected.subcategoryId,date,currency:ledger.profile.currency,amount_minor:parseAmount(amount,ledger.profile.currency),notes:notes.trim(),withdrawal:false});setAmount('');setNotes('');setSuccess('Expense saved.');amountRef.current?.focus();}catch(e){setError((e as Error).message);}finally{pending.current=false;}}
  return <section className="panel quick-expense" aria-labelledby="quick-expense-heading"><div className="panel-head"><div><h2 id="quick-expense-heading">Add an expense</h2><p>Amount, category, save. Today is already selected.</p></div><div className="quick-entry-types" aria-label="Other entry types">{(['income','saving','investment'] as const).map(kind=><button key={kind} type="button" className="text-button" disabled={busy} onClick={()=>more(kind)}>Add {kind==='saving'?'savings':kind}</button>)}</div></div><form onSubmit={submit}><div className="quick-expense-fields"><div className="amount-field"><label>Expense amount · {ledger.profile.currency}<input ref={amountRef} inputMode="decimal" placeholder="0.00" required value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);setSuccess('');}}/></label><AmountWords value={amount} currency={ledger.profile.currency}/></div><label>Expense category<select required value={choice} disabled={busy} onChange={e=>setChoice(e.target.value)}><option value="" disabled>Choose what you spent on</option>{choices.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label><button className="button" disabled={busy||!choices.length}><Plus size={18}/>{busy?'Saving…':'Save expense'}</button></div><details className="quick-expense-options"><summary>Change date or add a note</summary><div className="form-grid"><label>Expense date<input type="date" required min="1900-01-01" max="2100-12-31" disabled={busy} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Expense note (optional)<input maxLength={500} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What was it for?"/></label></div></details>{!choices.length&&<p className="info-note">Add an expense category in Categories to start recording.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p role="status" className="goal-status favorable">{success}</p>}</form></section>;
}
