import { useRef, useState, type FormEvent } from 'react';
import PaymentTypeField, {validatePaymentType} from './PaymentTypeField';
import { Plus } from 'lucide-react';
import { parseAmount, today, validDate } from './finance';
import type { Entry, Ledger } from './types';
import AmountWords from './AmountWords';
import { expenseChoices, customCategoryChoice } from './expenseChoices';
export default function QuickExpense({ ledger, busy, save }: {ledger:Ledger;busy:boolean;save:(entry:Entry,customName?:string)=>Promise<string>}) {
  const standardChoices=expenseChoices(ledger);
  const [customName,setCustomName]=useState(''); const [amount,setAmount]=useState(''); const [choice,setChoice]=useState('');
  const direct=ledger.categories.find(c=>c.id===choice&&c.kind==='expense'&&!c.archived);
  const choices=direct&&!standardChoices.some(c=>c.value===direct.id)?[{value:direct.id,label:direct.name+' (no subcategory)',categoryId:direct.id,subcategoryId:null},...standardChoices]:standardChoices;
  const [payment,setPayment]=useState('');
  const [date,setDate]=useState(today(ledger.profile.timezone));const [notes,setNotes]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');
  const draftId=useRef(crypto.randomUUID());const amountRef=useRef<HTMLInputElement>(null); const pending=useRef(false);
  async function submit(e:FormEvent){e.preventDefault();if(pending.current)return;pending.current=true;setError('');setSuccess('');try{const selected=choices.find(c=>c.value===choice);const custom=choice===customCategoryChoice;if(custom&&(!customName.trim()||customName.trim().length>60))throw new Error('Enter a category name between 1 and 60 characters.');if(!selected&&!custom)throw new Error('Choose an expense category or subcategory.');if(!validDate(date))throw new Error('Choose a valid date between 1900 and 2100.');await save({id:draftId.current,user_id:ledger.profile.user_id,category_id:selected?.categoryId??'',subcategory_id:selected?.subcategoryId??null,date,currency:ledger.profile.currency,amount_minor:parseAmount(amount,ledger.profile.currency),notes:notes.trim(),payment_method:validatePaymentType(payment),withdrawal:false},custom?customName.trim():undefined);draftId.current=crypto.randomUUID();setAmount('');setCustomName('');setChoice('');setNotes('');setSuccess('Expense saved.');amountRef.current?.focus();}catch(e){setError((e as Error).message);}finally{pending.current=false;}}
  return <section className="panel quick-expense" aria-labelledby="quick-expense-heading"><div className="panel-head"><div><h2 id="quick-expense-heading">Add an expense</h2><p>Amount, category, save. Today is already selected.</p></div></div><form onSubmit={submit}><div className="quick-expense-fields"><div className="amount-field"><label>Expense amount · {ledger.profile.currency}<input ref={amountRef} inputMode="decimal" placeholder="0.00" required value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);setSuccess('');}}/></label><AmountWords value={amount} currency={ledger.profile.currency}/></div><label>Expense category<select required value={choice} disabled={busy} onChange={e=>setChoice(e.target.value)}><option value="" disabled>Choose what you spent on</option>{choices.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}<option value={customCategoryChoice}>Other — enter a custom name</option></select></label>{choice===customCategoryChoice&&<label className="custom-category-name">Custom expense name<input required maxLength={60} disabled={busy} value={customName} onChange={e=>setCustomName(e.target.value)} placeholder="e.g. Office supplies"/><span className="small muted">Saved as an expense category you can choose again.</span></label>}<button className="button" disabled={busy}><Plus size={18}/>{busy?'Saving…':'Save expense'}</button></div><details className="quick-expense-options"><summary>Date, payment type & note</summary><div className="form-grid"><PaymentTypeField label="Expense payment type (optional)" value={payment} onChange={setPayment} disabled={busy}/><label>Expense date<input type="date" required min="1900-01-01" max="2100-12-31" disabled={busy} value={date} onChange={e=>setDate(e.target.value)} onInput={e=>setDate(e.currentTarget.value)}/></label><label>Expense note (optional)<input maxLength={500} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What was it for?"/></label></div></details>{!choices.length&&<p className="info-note">Choose Other to name your first expense category, or add one in Categories.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p role="status" className="goal-status favorable">{success}</p>}</form></section>;
}
