import {useState,type FormEvent} from 'react';
import {CalendarDays} from 'lucide-react';
import {currencies,type Currency,type Filter} from './types';
import {dateLabel,validDate,today} from './finance';
const months=Array.from({length:12},(_,i)=>new Date(2000,i,1).toLocaleString('en',{month:'long'}));
export function reportPeriodLabel(filter:Filter){return filter.startDate&&filter.endDate?`${dateLabel(filter.startDate)} – ${dateLabel(filter.endDate)}`:filter.year==='all'?'All history':filter.month==='all'?filter.year:`${months[Number(filter.month)-1]} ${filter.year}`;}
export default function ReportPeriod({filter,currency,years,change,changeCurrency}:{filter:Filter;currency:Currency;years:string[];change:(f:Filter)=>void;changeCurrency:(c:Currency)=>void}){
 const [range,setRange]=useState(false),[start,setStart]=useState(filter.startDate??`${filter.year==='all'?today().slice(0,4):filter.year}-${filter.month==='all'?'01':filter.month}-01`),[end,setEnd]=useState(filter.endDate??start),[error,setError]=useState('');
 const custom=!!filter.startDate;
 const regular={...filter,startDate:undefined,endDate:undefined};
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget),start=String(values.get('start')??''),end=String(values.get('end')??'');if(!validDate(start)||!validDate(end)||start>end){setError('Choose valid dates. The end must be on or after the start.');return;}change({...filter,startDate:start,endDate:end});setRange(false);setError('');}
 return <section className="report-period" aria-label="Reporting period"><div className="period-bar"><div className="period-title"><CalendarDays size={18}/><strong>{reportPeriodLabel(filter)}</strong></div><div className="period-controls">
 <label><span className="sr-only">Year</span><select aria-label="Year" value={filter.year} disabled={custom} onChange={e=>change({...regular,year:e.target.value,month:e.target.value==='all'?'all':filter.month})}><option value="all">All years</option>{years.map(y=><option key={y}>{y}</option>)}</select></label>
 <label><span className="sr-only">Month</span><select aria-label="Month" value={filter.month} disabled={custom||filter.year==='all'} onChange={e=>change({...regular,month:e.target.value})}><option value="all">Full year</option>{months.map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m}</option>)}</select></label>
 <label><span className="sr-only">Reporting currency</span><select aria-label="Reporting currency" value={currency} onChange={e=>changeCurrency(e.target.value as Currency)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label></div><button type="button" className="text-button range-toggle" aria-expanded={range} onClick={()=>{if(!range){const year=filter.year==='all'?today().slice(0,4):filter.year;const month=filter.month==='all'?'01':filter.month;setStart(filter.startDate??`${year}-${month}-01`);setEnd(filter.endDate??(filter.month==='all'?`${year}-12-31`:`${year}-${month}-${new Date(Date.UTC(Number(year),Number(month),0)).getUTCDate()}`));setError('');}setRange(!range);}}>Custom dates</button>{custom&&<button type="button" className="text-button" onClick={()=>change(regular)}>Use month / year</button>}</div>
 {range&&<form className="custom-range-form" onSubmit={submit}><label>From<input aria-label="Start date" name="start" type="date" min="1900-01-01" max="2100-12-31" value={start} onChange={e=>setStart(e.target.value)} onInput={e=>setStart(e.currentTarget.value)} required/></label><label>To<input aria-label="End date" name="end" type="date" min="1900-01-01" max="2100-12-31" value={end} onChange={e=>setEnd(e.target.value)} onInput={e=>setEnd(e.currentTarget.value)} required/></label><button className="button secondary">Apply dates</button>{error&&<p className="form-error" role="alert">{error}</p>}</form>}</section>;
}
